// StingTools — SLD Inline Annotation Commands (Phase 179)
//
// Inline annotation workflow for Single Line Diagram views. All commands
// operate on the active view (a drafting view generated by SLD_Generate, or a
// plan / section used as a schematic).
//
// Commands (all inline — no secondary windows):
//   SldAnnotate_All         — every annotatable element: cable / voltage / fault / load
//   SldAnnotate_Voltage     — voltage (ELC_CIR_VOLTAGE_TXT)
//   SldAnnotate_Current     — design current (ELC_CIR_DESIGN_CURRENT_TXT)
//   SldAnnotate_Fault       — fault level (ELC_CIR_FAULT_LEVEL_TXT)
//   SldAnnotate_Cable       — cable CSA + Ib + breaker
//   SldAnnotate_Phase       — L1/L2/L3/N/PE from the voltage
//   SldAnnotate_Load        — design load (ELC_CIR_DESIGN_LOAD_TXT)
//   SldAnnotate_Reference   — panel name + circuit ref
//   SldAnnotate_Impedance   — Zs
//   SldAnnotate_Diversity   — diversity factor
//   SldAnnotate_Format[_Compact|_Full|_Reference] — set the format and re-render
//   SldAnnotate_UpdateCalcs — refresh existing annotations from current values
//   SldAnnotate_Toggle      — halftone / restore the annotations
//   SldAnnotate_Clear       — delete the annotations
//   SldAnnotate_Audit       — annotated vs missing
//
// ELEC-10. Two things made this whole family dead on the SLD view:
//
//  1. Notes were "stamped" with STING_SLD_ANNOT_* shared parameters that exist
//     in no data file; the write fell into an empty catch, so Update / Toggle /
//     Clear / Audit found 0. Notes are now stamped with Extensible Storage
//     (StingSldAnnotStampSchema), which needs no binding.
//  2. ELC_CIR_* are bound to Electrical Equipment / Electrical Circuits, but an
//     SLD drafting view holds annotation SYMBOLS. SLDGenerator stamps each
//     symbol with STING_SLD_ELEMENT_ID (bound to all categories) = the source
//     equipment's ElementId. Values are now read from the element itself, then
//     that source equipment, then the source's supply circuit.

using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Electrical;
using Autodesk.Revit.UI;
using StingTools.Core;
using StingTools.Core.SLD;
using StingTools.Core.Storage;

namespace StingTools.Commands.Symbols
{
    // ── Shared engine ─────────────────────────────────────────────────────────

    internal static class SldAnnotationEngine
    {
        /// <summary>Set by SLDGenerator on each placed symbol: the source element's id.</summary>
        public const string SLD_SOURCE_PARAM = "STING_SLD_ELEMENT_ID";

        // Legacy stamp names. Never bound in any shipped data file, so nothing
        // should carry them — read only, in case a project bound them by hand.
        private const string LEGACY_KIND = "STING_SLD_ANNOT_KIND_TXT";
        private const string LEGACY_ELEM = "STING_SLD_ANNOT_ELEM_ID_TXT";

        // Session-level format preference (persisted per Revit session)
        public static SldAnnotFormat CurrentFormat { get; set; } = SldAnnotFormat.Compact;

        // ── Data sources ─────────────────────────────────────────────────────

        /// <summary>
        /// Where an element's electrical values live: the element, then (for an SLD
        /// symbol) the equipment it represents, then that equipment's supply circuit.
        /// </summary>
        public static List<Element> DataSources(Element el)
        {
            var list = new List<Element>();
            if (el == null) return list;
            list.Add(el);
            var doc = el.Document;
            Element source = null;
            try
            {
                string raw = el.LookupParameter(SLD_SOURCE_PARAM)?.AsString();
                if (long.TryParse(raw, out long sid) && sid > 0 && sid != el.Id.Value)
                    source = doc.GetElement(new ElementId(sid));
            }
            catch (Exception ex) { StingLog.Warn($"SldAnnotation source of {el.Id}: {ex.Message}"); }
            if (source != null) list.Add(source);

            var equipment = (source ?? el) as FamilyInstance;
            if (equipment?.MEPModel != null)
            {
                try
                {
                    // GetElectricalSystems on a panel is the circuit feeding it; on a
                    // load, the circuit(s) it is on. Circuits it FEEDS are excluded.
                    foreach (var s in equipment.MEPModel.GetElectricalSystems() ?? new HashSet<ElectricalSystem>())
                    {
                        if (s == null) continue;
                        try { if (s.BaseEquipment?.Id == equipment.Id) continue; } catch { }
                        list.Add(s);
                    }
                }
                catch (Exception ex) { StingLog.Warn($"SldAnnotation circuits of {equipment.Id}: {ex.Message}"); }
            }
            return list;
        }

        /// <summary>The first non-empty value of <paramref name="paramName"/> across the sources.</summary>
        public static string Get(IReadOnlyList<Element> sources, string paramName)
        {
            foreach (var s in sources)
            {
                string v = ParameterHelpers.GetString(s, paramName);
                if (!string.IsNullOrWhiteSpace(v)) return v;
            }
            return "";
        }

        public static string BuildAnnotText(Element el, SldAnnotKind kind, SldAnnotFormat fmt)
        {
            var sources = DataSources(el);
            return SldAnnotText.Build(kind, fmt, p => Get(sources, p));
        }

        // ── Element collection ────────────────────────────────────────────────

        /// <summary>Elements in the view with at least one SLD value (voltage, current,
        /// cable CSA or circuit ref) on themselves or their source equipment/circuit.</summary>
        public static List<Element> CollectAnnotatableElements(Document doc, View view)
        {
            var result = new List<Element>();
            int scanned = 0, symbols = 0;
            try
            {
                var col = new FilteredElementCollector(doc, view.Id).WhereElementIsNotElementType();
                foreach (var el in col)
                {
                    if (el == null || el is TextNote || el is View) continue;
                    if (el.Category == null) continue;
                    scanned++;
                    var sources = DataSources(el);
                    if (sources.Count > 1 && el.LookupParameter(SLD_SOURCE_PARAM) != null) symbols++;
                    if (SldAnnotText.DataParams.Any(p => !string.IsNullOrWhiteSpace(Get(sources, p))))
                        result.Add(el);
                }
                if (result.Count == 0 && scanned > 0)
                    StingLog.Warn($"SldAnnotationEngine.Collect: scanned {scanned} element(s) ({symbols} SLD symbol(s) " +
                        $"linked to source equipment) in '{view.Name}'; none carry any of " +
                        $"[{string.Join(", ", SldAnnotText.DataParams)}] on themselves, their source equipment " +
                        "or its supply circuit.");
            }
            catch (Exception ex) { StingLog.Warn($"SldAnnotationEngine.Collect: {ex.Message}"); }
            return result;
        }

        // ── Text note placement ───────────────────────────────────────────────

        /// <summary>Places a TextNote next to the element and stamps it (Extensible
        /// Storage) with kind + anchor + format for update / clear / audit.</summary>
        public static TextNote PlaceAnnotation(Document doc, View view, Element el,
            string text, SldAnnotKind kind, SldAnnotFormat fmt, double offsetFt = 0.5)
        {
            if (string.IsNullOrWhiteSpace(text)) return null;
            try
            {
                BoundingBoxXYZ bb = el.get_BoundingBox(view);
                XYZ centre = bb != null
                    ? (bb.Min + bb.Max) * 0.5
                    : (el.Location is LocationPoint lp ? lp.Point
                       : el.Location is LocationCurve lc ? lc.Curve.Evaluate(0.5, true)
                       : null);
                if (centre == null)
                {
                    StingLog.Warn($"SldAnnotation: element {el.Id} has no position in '{view.Name}' — not annotated.");
                    return null;
                }

                XYZ up = view.UpDirection ?? XYZ.BasisY;
                XYZ pos = centre + up.Multiply(offsetFt);

                var typeId = GetSmallestTextNoteType(doc);
                if (typeId == ElementId.InvalidElementId) return null;
                var tnOpts = new TextNoteOptions(typeId)
                {
                    HorizontalAlignment = HorizontalTextAlignment.Left,
                    KeepRotatedTextReadable = true,
                };

                var tn = TextNote.Create(doc, view.Id, pos, text, tnOpts);
                if (tn == null) return null;

                if (!StingSldAnnotStampSchema.Write(tn, new StingSldAnnotStampSchema.StampData
                    {
                        Kind = kind.ToString(),
                        AnchorUniqueId = el.UniqueId,
                        Format = fmt.ToString(),
                    }))
                {
                    // An unstamped note is invisible to Update / Clear / Audit — do not
                    // leave one behind claiming to be managed.
                    doc.Delete(tn.Id);
                    StingLog.Warn($"SldAnnotation: could not stamp the note for {el.Id}; removed it.");
                    return null;
                }
                return tn;
            }
            catch (Exception ex)
            {
                StingLog.Warn($"SldAnnotationEngine.PlaceAnnotation: {ex.Message}");
                return null;
            }
        }

        // Per document: an ElementId is only meaningful inside the document it came
        // from. The old single static field handed document A's type id to document B.
        private static readonly Dictionary<string, ElementId> _textTypeByDoc = new Dictionary<string, ElementId>();

        private static ElementId GetSmallestTextNoteType(Document doc)
        {
            string key = $"{doc.Title}|{doc.PathName}|{doc.GetHashCode()}";
            if (_textTypeByDoc.TryGetValue(key, out var cached)
                && cached != ElementId.InvalidElementId
                && doc.GetElement(cached) is TextNoteType)
                return cached;
            try
            {
                var smallest = new FilteredElementCollector(doc)
                    .OfClass(typeof(TextNoteType))
                    .Cast<TextNoteType>()
                    .OrderBy(t => t.get_Parameter(BuiltInParameter.TEXT_SIZE)?.AsDouble() ?? double.MaxValue)
                    .FirstOrDefault();
                if (smallest != null)
                {
                    _textTypeByDoc[key] = smallest.Id;
                    return smallest.Id;
                }
                StingLog.Warn("SldAnnotation: the document has no text note type.");
            }
            catch (Exception ex) { StingLog.Warn($"GetSmallestTextNoteType: {ex.Message}"); }
            return ElementId.InvalidElementId;
        }

        // ── Existing annotation management ────────────────────────────────────

        internal sealed class ExistingAnnotation
        {
            public TextNote Note;
            public SldAnnotKind Kind;
            public string AnchorUniqueId;
        }

        /// <summary>All STING SLD annotations on the view.</summary>
        public static List<ExistingAnnotation> CollectExistingAnnotations(Document doc, View view)
        {
            var result = new List<ExistingAnnotation>();
            try
            {
                foreach (var tn in new FilteredElementCollector(doc, view.Id).OfClass(typeof(TextNote)).Cast<TextNote>())
                {
                    var st = StingSldAnnotStampSchema.Read(tn);
                    if (st != null && SldAnnotText.TryParseKind(st.Kind, out var kind))
                    {
                        result.Add(new ExistingAnnotation { Note = tn, Kind = kind, AnchorUniqueId = st.AnchorUniqueId });
                        continue;
                    }
                    // Legacy parameter stamp (element id, not UniqueId).
                    string legacyElem = tn.LookupParameter(LEGACY_ELEM)?.AsString();
                    string legacyKind = tn.LookupParameter(LEGACY_KIND)?.AsString();
                    if (long.TryParse(legacyElem, out long lid) && SldAnnotText.TryParseKind(legacyKind, out var lk))
                    {
                        var anchor = doc.GetElement(new ElementId(lid));
                        if (anchor != null)
                            result.Add(new ExistingAnnotation { Note = tn, Kind = lk, AnchorUniqueId = anchor.UniqueId });
                    }
                }
            }
            catch (Exception ex) { StingLog.Warn($"SldAnnotationEngine.CollectExisting: {ex.Message}"); }
            return result;
        }

        /// <summary>Re-renders existing annotations from current values in
        /// <paramref name="fmt"/>. Returns (changed, orphaned, empty).</summary>
        public static (int Changed, int Orphaned, int Empty) UpdateAnnotations(Document doc, View view, SldAnnotFormat fmt)
        {
            int changed = 0, orphaned = 0, empty = 0;
            foreach (var a in CollectExistingAnnotations(doc, view))
            {
                try
                {
                    var el = doc.GetElement(a.AnchorUniqueId);
                    if (el == null) { orphaned++; continue; }

                    string newText = BuildAnnotText(el, a.Kind, fmt);
                    if (string.IsNullOrWhiteSpace(newText)) { empty++; continue; }
                    if (newText != (a.Note.Text ?? "").TrimEnd('\r', '\n'))
                    {
                        a.Note.Text = newText;
                        changed++;
                    }
                    StingSldAnnotStampSchema.Write(a.Note, new StingSldAnnotStampSchema.StampData
                    {
                        Kind = a.Kind.ToString(), AnchorUniqueId = a.AnchorUniqueId, Format = fmt.ToString(),
                    });
                }
                catch (Exception ex) { StingLog.Warn($"SldAnnotationEngine.Update: {ex.Message}"); }
            }
            return (changed, orphaned, empty);
        }

        /// <summary>Halftones (hide) or clears the override on (show) every STING SLD note.</summary>
        public static int ToggleAnnotationVisibility(Document doc, View view, bool show)
        {
            int n = 0;
            var ogs = new OverrideGraphicSettings();
            if (!show) ogs.SetHalftone(true);
            foreach (var a in CollectExistingAnnotations(doc, view))
            {
                try { view.SetElementOverrides(a.Note.Id, ogs); n++; }
                catch (Exception ex) { StingLog.Warn($"SldAnnotationEngine.Toggle {a.Note.Id}: {ex.Message}"); }
            }
            return n;
        }

        // ── Shared command body ───────────────────────────────────────────────

        internal static bool IsSchematicView(View v) =>
            v != null && !v.IsTemplate &&
            (v.ViewType == ViewType.DraftingView || v.ViewType == ViewType.FloorPlan ||
             v.ViewType == ViewType.EngineeringPlan || v.ViewType == ViewType.Section ||
             v.ViewType == ViewType.Detail);

        /// <summary>Annotate every annotatable element in the active view with one kind.</summary>
        internal static Result AnnotateKind(ExternalCommandData cd, SldAnnotKind kind, string label, double offsetFt)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;
            var doc = ctx.Doc;
            View view = ctx.UIDoc.ActiveView;
            if (!IsSchematicView(view))
            {
                TaskDialog.Show($"STING SLD — {label}",
                    "Active view is not a schematic/SLD-suitable view.\n" +
                    "Switch to a Drafting, Section, Floor Plan, or Engineering Plan view.");
                return Result.Succeeded;
            }

            var elements = CollectAnnotatableElements(doc, view);
            if (elements.Count == 0)
            {
                TaskDialog.Show($"STING SLD — {label}",
                    "No elements with electrical values (voltage, current, cable CSA, circuit reference) " +
                    "found in this view — on the elements, on the equipment an SLD symbol represents, " +
                    "or on that equipment's supply circuit.\n\n" +
                    "Populate ELC_CIR_* / ELC_CABLE_CSA_TXT first via the PANELS or CIRCTS workflows.");
                return Result.Succeeded;
            }

            // Skip elements already carrying this kind of annotation, so a second run
            // does not stack duplicates.
            var already = new HashSet<string>(CollectExistingAnnotations(doc, view)
                .Where(a => a.Kind == kind).Select(a => a.AnchorUniqueId));

            var fmt = CurrentFormat;
            int placed = 0, noValue = 0, duplicate = 0, failed = 0;
            using (var t = new Transaction(doc, $"STING SLD Annotate {label}"))
            {
                t.Start();
                foreach (var el in elements)
                {
                    if (already.Contains(el.UniqueId)) { duplicate++; continue; }
                    string text = BuildAnnotText(el, kind, fmt);
                    if (string.IsNullOrWhiteSpace(text)) { noValue++; continue; }
                    var tn = PlaceAnnotation(doc, view, el, text, kind, fmt, offsetFt);
                    if (tn != null) placed++; else failed++;
                }
                t.Commit();
            }
            StingLog.Info($"SldAnnotate {kind}: placed {placed}, no value {noValue}, already {duplicate}, failed {failed}");

            string msg = $"Placed {placed} {label} annotation(s) ({fmt} format).";
            if (duplicate > 0) msg += $"\n{duplicate} element(s) already had one — use 'SLD Update' to refresh them.";
            if (noValue > 0)   msg += $"\n{noValue} element(s) have no {label.ToLowerInvariant()} value to show.";
            if (failed > 0)    msg += $"\n{failed} could not be placed — see the STING log.";
            TaskDialog.Show($"STING SLD — {label}", msg);
            return Result.Succeeded;
        }
    }

    // ── Command implementations ───────────────────────────────────────────────

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateAllCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.All, "All", 0.5);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateVoltageCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Voltage, "Voltage", 0.5);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateCurrentCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Current, "Current", 0.5);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateFaultCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Fault, "Fault Level", 0.5);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateCableCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Cable, "Cable", 0.4);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotatePhaseCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Phase, "Phase", 0.6);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateLoadCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Load, "Load", 0.7);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateReferenceCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Reference, "Reference", -0.4);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateImpedanceCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Impedance, "Impedance", 0.8);
    }

    [Transaction(TransactionMode.Manual)] [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotateDiversityCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
            => SldAnnotationEngine.AnnotateKind(cd, SldAnnotKind.Diversity, "Diversity", 0.9);
    }

    /// <summary>
    /// Set the annotation format (Compact / Full / Reference) and re-render the
    /// active view's existing annotations in it. The three panel buttons
    /// (SldAnnotate_Format_Compact / _Full / _Reference) set
    /// <see cref="PendingFormat"/> first so each applies its own format; the plain
    /// SldAnnotate_Format tag shows the chooser. Before, all four opened the chooser.
    /// </summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotationFormatCommand : IExternalCommand
    {
        /// <summary>Consumed by the next Execute; null means "ask".</summary>
        internal static SldAnnotFormat? PendingFormat { get; set; }

        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;

            SldAnnotFormat chosen;
            var pending = PendingFormat;
            PendingFormat = null;
            if (pending.HasValue)
            {
                chosen = pending.Value;
            }
            else
            {
                var current = SldAnnotationEngine.CurrentFormat;
                var td = new TaskDialog("STING SLD — Annotation Format")
                {
                    MainInstruction = $"Current format: {current}",
                    MainContent = "Compact — cable/current/breaker on one line (e.g. 4mm² / 32A / B32)\n" +
                                  "Full    — verbose labels for each field (e.g. Cable: 4mm² | Ib: 32A)\n" +
                                  "Reference — circuit ref + panel name only",
                    CommonButtons = TaskDialogCommonButtons.Cancel,
                };
                td.AddCommandLink(TaskDialogCommandLinkId.CommandLink1, "Compact");
                td.AddCommandLink(TaskDialogCommandLinkId.CommandLink2, "Full");
                td.AddCommandLink(TaskDialogCommandLinkId.CommandLink3, "Reference only");
                var result = td.Show();
                if (result == TaskDialogResult.CommandLink1) chosen = SldAnnotFormat.Compact;
                else if (result == TaskDialogResult.CommandLink2) chosen = SldAnnotFormat.Full;
                else if (result == TaskDialogResult.CommandLink3) chosen = SldAnnotFormat.Reference;
                else return Result.Cancelled;
            }

            SldAnnotationEngine.CurrentFormat = chosen;

            var view = ctx.UIDoc.ActiveView;
            int existing = view == null ? 0 : SldAnnotationEngine.CollectExistingAnnotations(ctx.Doc, view).Count;
            string report = $"Format set to: {chosen}.";
            if (existing > 0)
            {
                (int Changed, int Orphaned, int Empty) r;
                using (var t = new Transaction(ctx.Doc, "STING SLD Annotation Format"))
                {
                    t.Start();
                    r = SldAnnotationEngine.UpdateAnnotations(ctx.Doc, view, chosen);
                    t.Commit();
                }
                report += $"\nRe-rendered {r.Changed} of {existing} annotation(s) in this view.";
                if (r.Empty > 0) report += $"\n{r.Empty} left as they were — no value to show in {chosen} format.";
                if (r.Orphaned > 0) report += $"\n{r.Orphaned} point at an element that no longer exists.";
            }
            else
            {
                report += "\nNo SLD annotations in this view yet; new annotations will use this format.";
            }
            StingLog.Info($"SldAnnotationFormat: {chosen}, {existing} existing");
            TaskDialog.Show("STING SLD — Format", report);
            return Result.Succeeded;
        }
    }

    /// <summary>Refresh existing SLD annotations from current parameter values.</summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SldUpdateFromCalcsCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;

            var view = ctx.UIDoc.ActiveView;
            var existing = SldAnnotationEngine.CollectExistingAnnotations(ctx.Doc, view);
            if (existing.Count == 0)
            {
                TaskDialog.Show("STING SLD — Update",
                    "No STING SLD annotations found in this view.\nRun 'SLD Annotate All' first.");
                return Result.Succeeded;
            }

            (int Changed, int Orphaned, int Empty) r;
            using (var t = new Transaction(ctx.Doc, "STING SLD Update Annotations"))
            {
                t.Start();
                r = SldAnnotationEngine.UpdateAnnotations(ctx.Doc, view, SldAnnotationEngine.CurrentFormat);
                t.Commit();
            }
            string report = $"Updated {r.Changed} of {existing.Count} annotation(s) from current values " +
                            $"({existing.Count - r.Changed - r.Orphaned - r.Empty} already current).";
            if (r.Empty > 0) report += $"\n{r.Empty} now have no value; their old text was kept.";
            if (r.Orphaned > 0) report += $"\n{r.Orphaned} point at an element that no longer exists — use Clear and re-annotate.";
            TaskDialog.Show("STING SLD — Update", report);
            return Result.Succeeded;
        }
    }

    /// <summary>Show / hide STING SLD annotations in the active view.</summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotationToggleCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;

            var view = ctx.UIDoc.ActiveView;
            var existing = SldAnnotationEngine.CollectExistingAnnotations(ctx.Doc, view);
            if (existing.Count == 0)
            {
                TaskDialog.Show("STING SLD — Toggle", "No STING SLD annotations found in this view.");
                return Result.Succeeded;
            }

            var td = new TaskDialog("STING SLD — Toggle Visibility")
            {
                MainInstruction = $"{existing.Count} SLD annotation(s) found.",
                CommonButtons = TaskDialogCommonButtons.Cancel,
            };
            td.AddCommandLink(TaskDialogCommandLinkId.CommandLink1, "Show (remove halftone)");
            td.AddCommandLink(TaskDialogCommandLinkId.CommandLink2, "Hide (halftone / grey out)");

            var result = td.Show();
            bool show = result == TaskDialogResult.CommandLink1;
            bool hide = result == TaskDialogResult.CommandLink2;
            if (!show && !hide) return Result.Succeeded;

            int n;
            using (var t = new Transaction(ctx.Doc, "STING SLD Toggle Visibility"))
            {
                t.Start();
                n = SldAnnotationEngine.ToggleAnnotationVisibility(ctx.Doc, view, show);
                t.Commit();
            }
            TaskDialog.Show("STING SLD — Toggle",
                $"{n} of {existing.Count} annotation(s) {(show ? "shown" : "halftoned")}.");
            return Result.Succeeded;
        }
    }

    /// <summary>Remove all STING SLD annotations from the active view.</summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotationClearCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;

            var view = ctx.UIDoc.ActiveView;
            var existing = SldAnnotationEngine.CollectExistingAnnotations(ctx.Doc, view);
            if (existing.Count == 0)
            {
                TaskDialog.Show("STING SLD — Clear", "No STING SLD annotations found in this view.");
                return Result.Succeeded;
            }

            var confirm = TaskDialog.Show("STING SLD — Clear Annotations",
                $"Delete {existing.Count} SLD annotation(s) from '{view.Name}'?\n" +
                "Only notes placed by the SLD annotate commands are removed.",
                TaskDialogCommonButtons.Yes | TaskDialogCommonButtons.No);
            if (confirm != TaskDialogResult.Yes) return Result.Succeeded;

            int deleted = 0;
            using (var t = new Transaction(ctx.Doc, "STING SLD Clear Annotations"))
            {
                t.Start();
                foreach (var a in existing)
                {
                    try { ctx.Doc.Delete(a.Note.Id); deleted++; }
                    catch (Exception ex) { StingLog.Warn($"SldAnnotationClear: {ex.Message}"); }
                }
                t.Commit();
            }
            TaskDialog.Show("STING SLD — Clear", $"Removed {deleted} of {existing.Count} annotation(s).");
            return Result.Succeeded;
        }
    }

    /// <summary>Audit report: which elements have annotations vs missing.</summary>
    [Transaction(TransactionMode.ReadOnly)]
    [Regeneration(RegenerationOption.Manual)]
    public class SldAnnotationAuditCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData cd, ref string msg, ElementSet els)
        {
            var ctx = ParameterHelpers.GetContext(cd);
            if (ctx == null) return Result.Failed;

            var view = ctx.UIDoc.ActiveView;
            var annotatable = SldAnnotationEngine.CollectAnnotatableElements(ctx.Doc, view);
            var existing    = SldAnnotationEngine.CollectExistingAnnotations(ctx.Doc, view);

            var annotatedIds = new HashSet<string>(existing.Select(a => a.AnchorUniqueId));
            int annotated   = annotatable.Count(el => annotatedIds.Contains(el.UniqueId));
            int unannotated = annotatable.Count - annotated;
            int orphaned    = existing.Count(a => ctx.Doc.GetElement(a.AnchorUniqueId) == null);

            string report = $"SLD Annotation Audit — '{view.Name}'\n\n" +
                $"Elements with electrical values:      {annotatable.Count}\n" +
                $"  Annotated:                          {annotated}\n" +
                $"  Missing annotations:                {unannotated}\n" +
                $"STING SLD notes in view:              {existing.Count}\n" +
                (orphaned > 0 ? $"  Pointing at deleted elements:       {orphaned}\n" : "") +
                $"Current annotation format:            {SldAnnotationEngine.CurrentFormat}\n\n" +
                (annotatable.Count == 0
                    ? "No element in this view carries SLD values — annotate has nothing to work from."
                    : unannotated > 0
                        ? "Run 'SLD Annotate All' to fill missing annotations."
                        : "All annotatable elements have annotations.");
            TaskDialog.Show("STING SLD — Annotation Audit", report);
            return Result.Succeeded;
        }
    }
}
