// StingTools v4 MVP — Fabrication export commands.
//
// Three thin IExternalCommand wrappers that re-emit the CSV sidecars
// produced by the per-discipline fabricators. Useful for re-export
// after manual model edits without regenerating sheets.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using StingTools.Core;
using StingTools.Core.Fabrication;
using StingTools.Core.Fabrication.Duct;
using StingTools.Core.Fabrication.Electrical;
using StingTools.Core.Fabrication.Pipe;

namespace StingTools.Commands.Fabrication
{
    [Transaction(TransactionMode.ReadOnly)]
    [Regeneration(RegenerationOption.Manual)]
    public class ExportCutListCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var ctx = ParameterHelpers.GetContext(commandData);
            if (ctx == null) { message = "No active document."; return Result.Failed; }
            var doc = ctx.Doc;
            try
            {
                var ids = AllPipeIds(doc);
                if (ids.Count == 0)
                {
                    TaskDialog.Show("STING v4 — Export Cut List",
                        "No pipe elements found in the project.");
                    return Result.Cancelled;
                }
                string outDir = OutputLocationHelper.GetOutputDirectory(doc);
                Directory.CreateDirectory(outDir);
                string path = Path.Combine(outDir, "STING_v4_pipe_cut_list.csv");
                using (var w = new StreamWriter(path, false))
                {
                    w.WriteLine("element_id,system,size_mm,length_mm,material,mitre_angle_deg");
                    foreach (var id in ids)
                    {
                        var el = doc.GetElement(id);
                        if (!(el is Autodesk.Revit.DB.Plumbing.Pipe p)) continue;
                        string sys = ReadString(p, "PLM_SYS_TXT");
                        double diaFt; try { diaFt = p.Diameter; } catch { diaFt = 0; }
                        double lenFt; try { lenFt = ((p.Location as LocationCurve)?.Curve?.Length) ?? 0; } catch { lenFt = 0; }
                        string mat = ReadString(p, "PLM_PPE_MAT_TXT");
                        w.WriteLine($"{id.Value},{sys},{(diaFt*304.8):F0},{(lenFt*304.8):F0},{mat},");
                    }
                }
                TaskDialog.Show("STING v4 — Export Cut List", $"Exported {ids.Count} pipes to:\n{path}");
                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                StingLog.Error("ExportCutListCommand failed", ex);
                message = ex.Message;
                return Result.Failed;
            }
        }

        private static List<ElementId> AllPipeIds(Document doc)
        {
            var ids = new List<ElementId>();
            try
            {
                foreach (var el in new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_PipeCurves)
                    .WhereElementIsNotElementType()) ids.Add(el.Id);
            }
            catch (Exception ex) { StingLog.Warn($"ExportCutListCommand: {ex.Message}"); }
            return ids;
        }

        private static string ReadString(Element el, string param)
        { try { return el?.LookupParameter(param)?.AsString() ?? ""; } catch { return ""; } }
    }

    [Transaction(TransactionMode.ReadOnly)]
    [Regeneration(RegenerationOption.Manual)]
    public class ExportIsometricsCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var ctx = ParameterHelpers.GetContext(commandData);
            if (ctx == null) { message = "No active document."; return Result.Failed; }
            var doc = ctx.Doc;
            try
            {
                // Collect every assembly view sheet generated by the
                // ShopDrawingComposer (sheet number starts with "SP-").
                var sheets = new FilteredElementCollector(doc).OfClass(typeof(ViewSheet))
                    .Cast<ViewSheet>()
                    .Where(s => s.SheetNumber?.StartsWith("SP-", StringComparison.OrdinalIgnoreCase) == true)
                    .Select(s => s.Id).ToList();
                if (sheets.Count == 0)
                {
                    TaskDialog.Show("STING v4 — Export Isometrics",
                        "No SP-... shop drawing sheets found. Run Generate Fabrication Package first.");
                    return Result.Cancelled;
                }

                string outDir = OutputLocationHelper.GetOutputDirectory(doc);
                Directory.CreateDirectory(outDir);
                string path = Path.Combine(outDir, "STING_v4_isometric_sheet_index.csv");
                using (var w = new StreamWriter(path, false))
                {
                    w.WriteLine("sheet_id,sheet_number,name");
                    foreach (var id in sheets)
                    {
                        var s = doc.GetElement(id) as ViewSheet;
                        if (s == null) continue;
                        w.WriteLine($"{id.Value},{s.SheetNumber},{(s.Name ?? "").Replace(',', ';')}");
                    }
                }
                TaskDialog.Show("STING v4 — Export Isometrics",
                    $"Indexed {sheets.Count} shop drawing sheets to:\n{path}\n\n" +
                    "PDF export is delegated to the existing Print → PDF batch path.");
                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                StingLog.Error("ExportIsometricsCommand failed", ex);
                message = ex.Message;
                return Result.Failed;
            }
        }
    }

    [Transaction(TransactionMode.ReadOnly)]
    [Regeneration(RegenerationOption.Manual)]
    public class ExportWeldMapCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var ctx = ParameterHelpers.GetContext(commandData);
            if (ctx == null) { message = "No active document."; return Result.Failed; }
            var doc = ctx.Doc;
            try
            {
                // Re-runs PipeFabricator-side weld map without regenerating
                // assemblies. Collects every pipe + fitting in scope.
                var ids = new List<ElementId>();
                foreach (var el in new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_PipeCurves)
                    .WhereElementIsNotElementType()) ids.Add(el.Id);
                foreach (var el in new FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_PipeFitting)
                    .WhereElementIsNotElementType()) ids.Add(el.Id);
                if (ids.Count == 0)
                {
                    TaskDialog.Show("STING v4 — Export Weld Map", "No pipe / fitting elements in project.");
                    return Result.Cancelled;
                }
                var fakeResult = new FabricationResult();
                new PipeFabricator().GetType()
                    .GetMethod("EmitWeldMapCsv", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                    ?.Invoke(new PipeFabricator(), new object[] { doc, ids, fakeResult });
                TaskDialog.Show("STING v4 — Export Weld Map",
                    $"Weld map regenerated for {ids.Count} elements.\n\nWarnings: {fakeResult.Warnings.Count}\n\n" +
                    "See output dir from Set Output Directory.");
                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                StingLog.Error("ExportWeldMapCommand failed", ex);
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}
