// StingTools — assign keynote values from classification (Phase G).
//
//   Keynote_Assign — closes the "keynotes never auto-populated" gap. For each
//   element (selection, else whole model) it derives a keynote KEY and writes it
//   to both the native Revit keynote (so keynote tags resolve against the
//   STING keynote table generated by KeynoteSync) and the STING ASS_KEYNOTE_TXT
//   (so TAG7 Section F shows it). Key preference:
//     1. CSI_SECTION_TXT  (e.g. "23 31 00")  — matches the CSI rows KeynoteSync emits
//     2. SYS token        (ASS_SYSTEM_TYPE_TXT, e.g. "HVAC") — matches the SYS rows
//   Run CSI_Assign + KeynoteSync first; then this; then load the table via
//   Annotate ▸ Keynoting Settings.

using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using StingTools.Core;
using StingTools.UI;

namespace StingTools.Commands.Classification
{
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class KeynoteAssignCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            try
            {
                var ctx = ParameterHelpers.GetContext(commandData);
                var doc = ctx?.Doc;
                if (doc == null) { message = "No active document."; return Result.Failed; }

                ICollection<ElementId> sel = null;
                try { sel = ctx.UIDoc?.Selection?.GetElementIds(); } catch { }
                bool scoped = sel != null && sel.Count > 0;

                IEnumerable<Element> targets = scoped
                    ? sel.Select(doc.GetElement).Where(e => e?.Category != null)
                    : new FilteredElementCollector(doc).WhereElementIsNotElementType()
                        .Where(e => e.Category != null && e.Category.HasMaterialQuantities);

                int fromCsi = 0, fromSys = 0, none = 0, total = 0;
                using (var t = new Transaction(doc, "STING Assign Keynotes"))
                {
                    t.Start();
                    foreach (var el in targets)
                    {
                        total++;
                        string csi = ParameterHelpers.GetString(el, ParamRegistry.CSI_SECTION);
                        string key = !string.IsNullOrWhiteSpace(csi)
                            ? csi.Trim()
                            : ParameterHelpers.GetString(el, ParamRegistry.SYS)?.Trim();
                        if (string.IsNullOrWhiteSpace(key)) { none++; continue; }

                        // STING param (TAG7 display) — SetIfEmpty preserves manual edits.
                        try { ParameterHelpers.SetIfEmpty(el, ParamRegistry.KEYNOTE, key); } catch { }
                        // Native Revit keynote so keynote tags resolve against the table.
                        try
                        {
                            var p = el.get_Parameter(BuiltInParameter.KEYNOTE_PARAM);
                            if (p != null && !p.IsReadOnly && p.StorageType == StorageType.String &&
                                string.IsNullOrWhiteSpace(p.AsString()))
                                p.Set(key);
                        }
                        catch { }

                        if (!string.IsNullOrWhiteSpace(csi)) fromCsi++; else fromSys++;
                    }
                    t.Commit();
                }

                var panel = StingResultPanel.Create("MEP / Classification — Assign Keynotes");
                panel.SetSubtitle($"{fromCsi + fromSys} keynoted of {total} ({(scoped ? "selection" : "whole model")})");
                panel.AddSection("SUMMARY")
                     .Metric("From CSI section", fromCsi.ToString())
                     .Metric("From SYS token",   fromSys.ToString())
                     .Metric("No classification", none.ToString());
                panel.AddSection("NEXT");
                panel.Text("Run KeynoteSync to (re)generate STING_KEYNOTES.txt (now includes CSI sections), " +
                           "then load it via Annotate ▸ Keynoting Settings so keynote tags resolve.");
                panel.Show();

                StingLog.Info($"Keynote assign: csi={fromCsi} sys={fromSys} none={none} total={total}");
                return Result.Succeeded;
            }
            catch (Exception ex)
            {
                StingLog.Error("KeynoteAssignCommand", ex);
                message = ex.Message;
                return Result.Failed;
            }
        }
    }
}
