// StingTools — one vocabulary and one reader for transmittals.json rows
//
// Three writers produce transmittal rows and they never agreed:
//
//   * BIMManagerEngine.CreateTransmittal  — transmittal_id, date_issued,
//     to_organization, document_ids, status "ISSUED"
//   * Document Manager Quick Transmittal  — transmittal_id, date, recipient,
//     documents, status "DRAFT" / "SENT"
//   * ProjectFolderEngine auto-transmittal — id, issue_date, recipients,
//     documents, status "AUTO_GENERATED"
//
// The Document Manager read only the second shape, and coerced any status it did
// not know to DRAFT, so every MIDP model drop and every ACC publish showed as a
// DRAFT with no date, no recipient and zero documents (ROADMAP IM-17). Worse, the
// ACC publish recorded "ISSUED" for a ZIP that had only been built on local disk.
//
// This file is the vocabulary and the field reader; writers and readers use it.
// Revit-free; unit-tested (StingTools.Tags.Tests).

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace StingTools.BIMManager
{
    internal static class TransmittalStatus
    {
        public const string Draft = "DRAFT";
        /// <summary>A package was built but has not left the originator — e.g. an
        /// ACC publish ZIP waiting to be uploaded. Not a record of issue.</summary>
        public const string Prepared = "PREPARED";
        /// <summary>Recorded as issued by the originator (a MIDP drop).</summary>
        public const string Issued = "ISSUED";
        public const string Sent = "SENT";
        public const string Received = "RECEIVED";
        public const string Acknowledged = "ACKNOWLEDGED";
        public const string Signed = "SIGNED";
        public const string Rejected = "REJECTED";
        public const string Superseded = "SUPERSEDED";
        public const string AutoGenerated = "AUTO_GENERATED";
        public const string Void = "VOID";

        /// <summary>Every status a transmittal may carry, for pickers and validation.</summary>
        public static readonly IReadOnlyList<string> All = new[]
        {
            Draft, Prepared, Issued, Sent, Received, Acknowledged,
            Signed, Rejected, Superseded, AutoGenerated, Void,
        };

        private static readonly HashSet<string> Known = new HashSet<string>(All, StringComparer.OrdinalIgnoreCase);

        public static bool IsKnown(string status) => !string.IsNullOrWhiteSpace(status) && Known.Contains(status.Trim());

        /// <summary>The status to show. Empty is DRAFT (a row nobody has moved on).
        /// An unrecognised value is shown as written, upper-cased — never replaced by
        /// DRAFT, which is how every issued transmittal came to read as a draft.</summary>
        public static string Normalise(string status)
        {
            if (string.IsNullOrWhiteSpace(status)) return Draft;
            return status.Trim().ToUpperInvariant();
        }
    }

    /// <summary>Reads the fields every transmittal shape carries under different
    /// names. First non-empty spelling wins, in the order listed.</summary>
    internal static class TransmittalRecord
    {
        public static string Id(JToken t) => First(t, "transmittal_id", "id");

        /// <summary>
        /// The next free TX-NNNN id across EVERY row shape (transmittal_id, id, tx_id). KUT deep
        /// review ISO-12: five writers allocated ids five ways — Count+1, a process-static counter
        /// that restarted at 1 each Revit session, scans of one field only — so an auto row and a
        /// manual row could both be TX-0002, and MarkSent then found the wrong one.
        /// </summary>
        public static string NextId(JArray rows)
        {
            int max = 0;
            foreach (var r in rows?.OfType<JObject>() ?? Enumerable.Empty<JObject>())
                foreach (var key in new[] { "transmittal_id", "id", "tx_id" })
                {
                    string v = r[key]?.Type == JTokenType.String ? (string)r[key] : null;
                    if (v == null || !v.StartsWith("TX-", StringComparison.OrdinalIgnoreCase)) continue;
                    if (int.TryParse(v.Substring(3), System.Globalization.NumberStyles.None,
                            System.Globalization.CultureInfo.InvariantCulture, out int n) && n > max)
                        max = n;
                }
            return $"TX-{max + 1:D4}";
        }

        /// <summary>When the package was issued, or "" if it has not been (a PREPARED
        /// row). This is the date a title block may print.</summary>
        public static string IssueDate(JToken t) => First(t, "date_issued", "date", "issue_date");

        /// <summary>The date to list the row under: its issue date, else when it was prepared.</summary>
        public static string Date(JToken t)
        {
            string d = IssueDate(t);
            return !string.IsNullOrEmpty(d) ? d : First(t, "date_prepared");
        }

        public static string Recipient(JToken t)
        {
            string r = First(t, "recipient", "to_organization");
            if (!string.IsNullOrEmpty(r)) return r;
            if (t?["recipients"] is JArray arr)
                return string.Join("; ", arr.Select(x => x is JObject o ? (string)o["name"] ?? "" : x.ToString())
                                            .Where(s => !string.IsNullOrWhiteSpace(s)));
            return "";
        }

        /// <summary>Documents listed on the row: "documents" or "document_ids".</summary>
        public static JArray Documents(JToken t)
            => t?["documents"] as JArray ?? t?["document_ids"] as JArray ?? new JArray();

        public static string Suitability(JToken t) => First(t, "suitability", "suitability_code");

        public static string CreatedBy(JToken t) => First(t, "created_by", "issued_by", "from_organization");

        /// <summary>Mark the row with <paramref name="id"/> SENT, stamping the issue
        /// date and a history entry in the {from,to,by,at,note} shape CoordStores
        /// uses. Only a PREPARED or DRAFT row moves: a row that already went further
        /// (SENT, ACKNOWLEDGED…) is left alone, so re-uploading a bundle cannot rewind
        /// or re-date a record. Returns the row changed, or null.</summary>
        public static JObject MarkSent(JArray rows, string id, DateTime now, string user, string note)
        {
            if (rows == null || string.IsNullOrWhiteSpace(id)) return null;
            // The movable row with this id. Legacy files can hold two rows with one id (ISO-12);
            // taking the first match picked an AUTO_GENERATED duplicate and left the PREPARED
            // row unissued (ISO-13).
            var row = rows.OfType<JObject>()
                .Where(r => string.Equals(Id(r), id, StringComparison.OrdinalIgnoreCase))
                .FirstOrDefault(r =>
                {
                    string s = TransmittalStatus.Normalise(r["status"]?.ToString());
                    return s == TransmittalStatus.Prepared || s == TransmittalStatus.Draft;
                });
            if (row == null) return null;
            string from = TransmittalStatus.Normalise(row["status"]?.ToString());

            row["status"] = TransmittalStatus.Sent;
            row["date_issued"] = now.ToString("yyyy-MM-dd");
            row["sent_date"] = now.ToString("yyyy-MM-dd HH:mm");
            if (!(row["status_history"] is JArray hist))
            {
                hist = new JArray();
                string legacy = row["status_history"]?.Type == JTokenType.String ? row["status_history"].ToString() : null;
                if (!string.IsNullOrWhiteSpace(legacy)) hist.Add(new JObject { ["note"] = legacy, ["migrated"] = true });
                row["status_history"] = hist;
            }
            hist.Add(new JObject
            {
                ["from"] = from, ["to"] = TransmittalStatus.Sent,
                ["by"] = user ?? "", ["at"] = now.ToString("o", System.Globalization.CultureInfo.InvariantCulture),
                ["note"] = note ?? "",
            });
            return row;
        }

        private static string First(JToken t, params string[] keys)
        {
            if (!(t is JObject o)) return "";
            foreach (var k in keys)
            {
                var tok = o[k];
                string v;
                if (tok == null || tok.Type == JTokenType.Array || tok.Type == JTokenType.Object) v = null;
                // JArray.Parse turns "2026-09-22T10:00:00Z" into a Date token, whose
                // ToString() is the machine's culture ("09/22/2026 10:00:00"). Keep ISO.
                else if (tok.Type == JTokenType.Date)
                    v = ((DateTime)tok).ToString("yyyy-MM-ddTHH:mm:ssK", System.Globalization.CultureInfo.InvariantCulture);
                else v = tok.ToString();
                if (!string.IsNullOrWhiteSpace(v)) return v;
            }
            return "";
        }
    }
}
