namespace Planscape.Core.Entities;

/// <summary>
/// A materialised quantity line — one row per element per take-off rule
/// per BOQ baseline snapshot. This is the lowest level of the NRM2
/// BOQ: each row carries a section code, item description, unit,
/// quantity, optional unit rate, and a back-reference to the originating
/// IFC element so the BOQ can be re-derived deterministically from the
/// model at any point.
///
/// Rows are typically produced by the ingestion pipeline
/// (<c>IIfcQuantityIngestor</c>) which evaluates every project model's
/// elements against the active <see cref="TakeoffRule"/> set. They can
/// also be manually inserted for items not in the model (provisional
/// sums, dayworks, PC sums, preliminaries).
/// </summary>
public class QuantityLine : ITenantScoped
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid TenantId { get; set; }
    public Guid ProjectId { get; set; }

    /// <summary>
    /// Null = "live" line in the current draft BOQ. Set to a
    /// <see cref="BoqBaseline"/> id when frozen at issue (Stage 4 etc.).
    /// </summary>
    public Guid? BaselineId { get; set; }

    /// <summary>The NRM2/Uniclass section this line is filed under.</summary>
    public Guid ClassificationCodeId { get; set; }

    /// <summary>Take-off rule that produced this line — null for manual entries.</summary>
    public Guid? TakeoffRuleId { get; set; }

    /// <summary>Optional work-package scope (subcontractor split).</summary>
    public Guid? WorkPackageId { get; set; }

    // ── Source element (IFC/Revit traceability) ──

    /// <summary>Project model the element came from.</summary>
    public Guid? ProjectModelId { get; set; }

    /// <summary>IFC GlobalId (22-char base64) — primary key in the source IFC file.</summary>
    public string? IfcGlobalId { get; set; }

    /// <summary>IFC type — "IfcWall", "IfcSlab", etc.</summary>
    public string? IfcType { get; set; }

    /// <summary>Revit element id when sourced from a Revit model (not IFC).</summary>
    public long? RevitElementId { get; set; }

    public string? Level { get; set; }
    public string? Zone { get; set; }

    // ── NRM2 item description ──

    /// <summary>NRM2 section code redundantly cached for indexed queries.</summary>
    public string SectionCode { get; set; } = "";

    /// <summary>
    /// Full NRM2-format item description — generated by the
    /// description builder from the rule's template and element data.
    /// Single-row narrative, line breaks preserved as "\n".
    /// </summary>
    public string ItemDescription { get; set; } = "";

    public string Unit { get; set; } = "nr";

    /// <summary>Net take-off quantity before waste allowance.</summary>
    public double NetQuantity { get; set; }

    /// <summary>Waste percentage applied (matches the rule at ingest).</summary>
    public double WastePercent { get; set; }

    /// <summary>Gross quantity = NetQuantity × (1 + WastePercent/100).</summary>
    public double Quantity { get; set; }

    // ── Pricing ──

    public decimal? UnitRate { get; set; }
    public decimal? LineTotal { get; set; }
    public string Currency { get; set; } = "GBP";

    /// <summary>"Measured" / "ProvSum" / "PcSum" / "Daywork" / "Prelim" / "Variation".</summary>
    public string LineKind { get; set; } = "Measured";

    /// <summary>
    /// "Lump" / "Remeasure" — under JCT remeasurable contracts the
    /// final account quantity is re-measured from as-built; under lump-sum
    /// contracts the contractor takes the quantity risk.
    /// </summary>
    public string PricingBasis { get; set; } = "Lump";

    /// <summary>
    /// Embodied carbon coefficient (kgCO₂e per unit of measure) from
    /// the active material EPD or ICE Database. Renders the carbon
    /// parallel-BOQ without a second take-off pass.
    /// </summary>
    public double? EmbodiedCarbonPerUnit { get; set; }

    /// <summary>EmbodiedCarbonPerUnit × Quantity (kgCO₂e), cached for reports.</summary>
    public double? EmbodiedCarbonTotal { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public string? CreatedBy { get; set; }

    // Navigation
    public Project? Project { get; set; }
    public ClassificationCode? ClassificationCode { get; set; }
    public TakeoffRule? TakeoffRule { get; set; }
    public BoqBaseline? Baseline { get; set; }
    public WorkPackage? WorkPackage { get; set; }
    public ProjectModel? ProjectModel { get; set; }
}
