// StingTools — SLD riser diagram commands (Phase 175)
//
// SLD-11: DrawFeeders annotates feeder cable CSA on connection lines when
//         RiserOptions.ShowFeederCsa is true.
// SLD-17: CreateOrReplaceView purges existing view content before returning
//         so a re-generate replaces rather than overlays the previous diagram.
// SLD-18: DrawRiser groups nodes by their actual Revit level elevation rather
//         than BFS depth so the vertical position reflects the building storey.

using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using StingTools.Core;
using StingTools.UI;

namespace StingTools.Commands.SLD
{
    public struct RiserOptions
    {
        public string Layout;        // "Horizontal" | "Vertical"
        public bool ShowFaultKa;
        public bool ShowFeederCsa;
        public bool ShowLoadingPct;
    }

    /// <summary>
    /// Generates a horizontal riser diagram in a new (or replaced) ViewDrafting
    /// using FilledRegion boxes for panels and DetailCurve segments for feeders.
    /// Distinct from the vertical SLD generated by SLDGenerator.
    /// </summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SLDRiserDiagramCommand : IExternalCommand
    {
        private const string DrawingTypeId = "elec-riser-A2-1to100";

        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var ctx = ParameterHelpers.GetContext(commandData);
            if (ctx == null) { message = "No active document."; return Result.Failed; }
            var doc = ctx.Doc;

            var root = StingTools.Core.SLD.SLDCircuitTraverser.BuildHierarchy(doc);
            if (root == null)
            {
                TaskDialog.Show("STING Riser", "No SLD hierarchy found.");
                return Result.Cancelled;
            }
            var opts = StingElectricalCommandHandler.CurrentRiserOptions;

            ViewDrafting view = null;
            using (var tx = new Transaction(doc, "STING Generate Riser Diagram"))
            {
                tx.Start();
                // SLD-17: CreateOrReplaceView purges existing content on match
                view = CreateOrReplaceView(doc,
                    $"STING - Riser Diagram - {DateTime.Now:yyyyMMdd-HHmm}");
                if (view == null) { tx.RollBack(); message = "Could not create drafting view."; return Result.Failed; }
                DrawRiser(doc, view, root, opts);
                StampDrawingType(doc, view);
                tx.Commit();
            }

            if (view != null)
            {
                try { ctx.UIDoc.ActiveView = view; } catch { }
            }
            try { ComplianceScan.InvalidateCache(); } catch { }
            TaskDialog.Show("STING Riser", $"Riser diagram generated: '{view?.Name}'.");
            return Result.Succeeded;
        }

        // SLD-17: if a view with the same name exists, clear its content; otherwise create fresh
        private static ViewDrafting CreateOrReplaceView(Document doc, string name)
        {
            try
            {
                var existing = new FilteredElementCollector(doc)
                    .OfClass(typeof(ViewDrafting)).Cast<ViewDrafting>()
                    .FirstOrDefault(v =>
                        string.Equals(v.Name, name, StringComparison.OrdinalIgnoreCase));

                if (existing != null)
                {
                    // Purge all elements inside so the view is redrawn from scratch
                    var contentIds = new FilteredElementCollector(doc, existing.Id)
                        .ToElementIds().ToList();
                    if (contentIds.Count > 0)
                    {
                        try { doc.Delete(contentIds); }
                        catch (Exception ex) { StingLog.Warn($"CreateOrReplaceView purge: {ex.Message}"); }
                    }
                    return existing;
                }

                var vft = new FilteredElementCollector(doc)
                    .OfClass(typeof(ViewFamilyType)).Cast<ViewFamilyType>()
                    .FirstOrDefault(t => t.ViewFamily == ViewFamily.Drafting);
                if (vft == null) return null;
                var v = ViewDrafting.Create(doc, vft.Id);
                try { v.Name = name; } catch { }
                return v;
            }
            catch (Exception ex) { StingLog.Warn($"CreateOrReplaceView: {ex.Message}"); return null; }
        }

        internal static void DrawRiser(Document doc, ViewDrafting view,
            StingTools.Core.SLD.SLDNode root, RiserOptions opts)
        {
            const double mmPerFt = 304.8;
            double boxWmm = 40, boxHmm = 60, hSpacingMm = 80, vSpacingMm = 20;
            double boxW = boxWmm / mmPerFt, boxH = boxHmm / mmPerFt;
            double hSpacing = hSpacingMm / mmPerFt, vSpacing = vSpacingMm / mmPerFt;

            // SLD-18: group nodes by actual Revit level elevation (highest storey = row 0)
            // rather than BFS traversal depth.
            var elevToNodes = new SortedDictionary<double, List<StingTools.Core.SLD.SLDNode>>(
                Comparer<double>.Create((a, b) => b.CompareTo(a))); // descending → top of diagram first

            void CollectByElevation(StingTools.Core.SLD.SLDNode n)
            {
                double elev = ResolveElevation(doc, n);
                if (!elevToNodes.ContainsKey(elev))
                    elevToNodes[elev] = new List<StingTools.Core.SLD.SLDNode>();
                elevToNodes[elev].Add(n);
                foreach (var c in n.Children ?? Enumerable.Empty<StingTools.Core.SLD.SLDNode>())
                    CollectByElevation(c);
            }
            CollectByElevation(root);

            var levels = elevToNodes.Values.ToList();

            bool vertical = string.Equals(opts.Layout, "Vertical", StringComparison.OrdinalIgnoreCase);
            var positions = new Dictionary<long, XYZ>();
            for (int i = 0; i < levels.Count; i++)
            {
                var col = levels[i];
                for (int j = 0; j < col.Count; j++)
                {
                    double x = vertical ? j * (boxW + hSpacing) : i * (boxW + hSpacing);
                    double y = vertical ? -i * (boxH + vSpacing) : -j * (boxH + vSpacing);
                    var node = col[j];
                    if (node.ElementId != null && node.ElementId != ElementId.InvalidElementId)
                        positions[node.ElementId.Value] = new XYZ(x, y, 0);
                    DrawBox(doc, view, x, y, boxW, boxH, node, opts);
                }
            }

            DrawFeeders(doc, view, root, positions, boxW, boxH, vertical, opts);
        }

        // SLD-18: resolve node elevation from its RevitElement's Level
        private static double ResolveElevation(Document doc, StingTools.Core.SLD.SLDNode n)
        {
            try
            {
                if (n.RevitElement == null) return 0;
                var lv = doc.GetElement(n.RevitElement.LevelId) as Level;
                if (lv != null) return lv.Elevation;
            }
            catch { }
            return 0;
        }

        private static void DrawBox(Document doc, ViewDrafting view,
            double x, double y, double w, double h,
            StingTools.Core.SLD.SLDNode node, RiserOptions opts)
        {
            try
            {
                var loop = new CurveLoop();
                var p1 = new XYZ(x, y, 0);
                var p2 = new XYZ(x + w, y, 0);
                var p3 = new XYZ(x + w, y + h, 0);
                var p4 = new XYZ(x, y + h, 0);
                loop.Append(Line.CreateBound(p1, p2));
                loop.Append(Line.CreateBound(p2, p3));
                loop.Append(Line.CreateBound(p3, p4));
                loop.Append(Line.CreateBound(p4, p1));
                var frt = new FilteredElementCollector(doc)
                    .OfClass(typeof(FilledRegionType)).Cast<FilledRegionType>().FirstOrDefault();
                if (frt != null)
                    FilledRegion.Create(doc, frt.Id, view.Id, new List<CurveLoop> { loop });

                var ts = new FilteredElementCollector(doc)
                    .OfClass(typeof(TextNoteType)).Cast<TextNoteType>().FirstOrDefault();
                if (ts != null)
                {
                    string label = node.Label ?? "(panel)";
                    if (!string.IsNullOrEmpty(node.Rating)) label += $"\n{node.Rating}";
                    TextNote.Create(doc, view.Id, new XYZ(x + w / 2, y + h / 2, 0), label, ts.Id);
                }

                if (opts.ShowFaultKa && node.RevitElement != null)
                {
                    string fk = ParameterHelpers.GetString(node.RevitElement, ParamRegistry.ELC_PNL_FAULT_KA);
                    if (!string.IsNullOrEmpty(fk) && ts != null)
                        TextNote.Create(doc, view.Id,
                            new XYZ(x + w / 2, y - h * 0.15, 0), $"Iₖ {fk} kA", ts.Id);
                }
                if (opts.ShowLoadingPct && node.LoadKW > 0 && ts != null)
                {
                    int pct = (int)Math.Min(100, node.LoadKW);
                    TextNote.Create(doc, view.Id,
                        new XYZ(x + w / 2, y - h * 0.30, 0), $"≈ {pct}% load", ts.Id);
                }
            }
            catch (Exception ex) { StingLog.Warn($"DrawBox: {ex.Message}"); }
        }

        private static void DrawFeeders(Document doc, ViewDrafting view,
            StingTools.Core.SLD.SLDNode root, Dictionary<long, XYZ> positions,
            double boxW, double boxH, bool vertical, RiserOptions opts)
        {
            // Resolve TextNoteType once for CSA labels
            var ts = (opts.ShowFeederCsa)
                ? new FilteredElementCollector(doc)
                      .OfClass(typeof(TextNoteType)).Cast<TextNoteType>().FirstOrDefault()
                : null;

            void Walk(StingTools.Core.SLD.SLDNode n)
            {
                if (n == null) return;
                foreach (var c in n.Children ?? Enumerable.Empty<StingTools.Core.SLD.SLDNode>())
                {
                    try
                    {
                        if (n.ElementId != null && c.ElementId != null
                            && n.ElementId != ElementId.InvalidElementId
                            && c.ElementId != ElementId.InvalidElementId
                            && positions.TryGetValue(n.ElementId.Value, out var pa)
                            && positions.TryGetValue(c.ElementId.Value, out var pb))
                        {
                            var start = new XYZ(pa.X + boxW, pa.Y + boxH / 2, 0);
                            var end   = new XYZ(pb.X,        pb.Y + boxH / 2, 0);
                            if (start.DistanceTo(end) > 1e-6)
                            {
                                doc.Create.NewDetailCurve(view, Line.CreateBound(start, end));

                                // SLD-11: annotate feeder cable CSA on the connection line
                                if (opts.ShowFeederCsa && c.RevitElement != null && ts != null)
                                {
                                    string csa = ParameterHelpers.GetString(
                                        c.RevitElement, ParamRegistry.ELC_CKT_CSA_MM2);
                                    if (string.IsNullOrEmpty(csa))
                                        csa = ParameterHelpers.GetString(c.RevitElement, "ELC_CDT_CSA_MM2");
                                    if (!string.IsNullOrEmpty(csa))
                                    {
                                        // Place label mid-line, slightly above
                                        double mx = (start.X + end.X) * 0.5;
                                        double my = (start.Y + end.Y) * 0.5 + boxH * 0.08;
                                        TextNote.Create(doc, view.Id, new XYZ(mx, my, 0), csa, ts.Id);
                                    }
                                }
                            }
                        }
                    }
                    catch (Exception ex) { StingLog.Warn($"DrawFeeder: {ex.Message}"); }
                    Walk(c);
                }
            }
            Walk(root);
        }

        private static void StampDrawingType(Document doc, ViewDrafting view)
        {
            try
            {
                var t = Type.GetType("StingTools.Core.Drawing.DrawingTypeStamper");
                t?.GetMethod("Stamp", new[] { typeof(Element), typeof(string) })
                  ?.Invoke(null, new object[] { view, DrawingTypeId });
            }
            catch (Exception ex) { StingLog.Warn($"StampDrawingType: {ex.Message}"); }
        }
    }

    /// <summary>
    /// Replaces the contents of an existing "STING - Riser Diagram*" view in
    /// place so any sheet placement is preserved.
    /// </summary>
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class SLDUpdateRiserCommand : IExternalCommand
    {
        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)
        {
            var ctx = ParameterHelpers.GetContext(commandData);
            if (ctx == null) { message = "No active document."; return Result.Failed; }
            var doc = ctx.Doc;

            var view = new FilteredElementCollector(doc)
                .OfClass(typeof(ViewDrafting)).Cast<ViewDrafting>()
                .FirstOrDefault(v => (v.Name ?? "").StartsWith("STING - Riser Diagram",
                    StringComparison.OrdinalIgnoreCase));
            if (view == null)
            {
                TaskDialog.Show("STING Riser", "No existing riser diagram view found. Run Generate first.");
                return Result.Cancelled;
            }

            using (var tx = new Transaction(doc, "STING Update Riser Diagram"))
            {
                tx.Start();
                var viewElems = new FilteredElementCollector(doc, view.Id).ToElementIds().ToList();
                if (viewElems.Count > 0)
                {
                    try { doc.Delete(viewElems); }
                    catch (Exception ex) { StingLog.Warn($"Riser purge: {ex.Message}"); }
                }
                var root = StingTools.Core.SLD.SLDCircuitTraverser.BuildHierarchy(doc);
                if (root != null)
                {
                    var opts = StingElectricalCommandHandler.CurrentRiserOptions;
                    SLDRiserDiagramCommand.DrawRiser(doc, view, root, opts);
                }
                tx.Commit();
            }
            TaskDialog.Show("STING Riser", $"Updated '{view.Name}'.");
            return Result.Succeeded;
        }
    }
}
