ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS device_id TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'desktop';
