// DTW-164 — every integer filter rule must compare against the enum member it means.
//
// STING_AEC_FILTERS.json compared STRUCTURAL_MATERIAL_TYPE / WALL_STRUCTURAL_USAGE_PARAM /
// INSTANCE_STRUCT_USAGE_PARAM / FUNCTION_PARAM against bare integers written from memory:
// "Concrete" was 1 (Steel) and "Steel" was 2 (Concrete), "Masonry" was 5 (PrecastConcrete),
// "Shear" was 3 (Combined), "Retaining" was 4 (no member), "Bracing" was 4 (Joist),
// "Cladding" was wall function 3 (Retaining). Every one built a valid filter that
// highlighted the wrong elements.
//
// The data now names the member ("enum" + "valueName"), and this test checks the
// integer against RevitAPI.dll's own value (Fixtures/RevitEnumValues.txt, generated by
// tools/DumpBuiltInParameterNames). A wrong integer, or an integer rule on an
// enum-valued parameter that does not say which member it means, fails here.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using Xunit;

namespace StingTools.Tags.Tests
{
    public class RevitEnumValueTests
    {
        /// <summary>Enum-valued built-in parameter → the Revit enum its integer is a member of.</summary>
        private static readonly Dictionary<string, string> EnumParams = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["STRUCTURAL_MATERIAL_TYPE"]    = "StructuralMaterialType",
            ["WALL_STRUCTURAL_USAGE_PARAM"] = "StructuralWallUsage",
            ["INSTANCE_STRUCT_USAGE_PARAM"] = "StructuralInstanceUsage",
            ["FUNCTION_PARAM"]              = "WallFunction",
        };

        /// <summary>
        /// STRUCTURAL_MATERIAL_TYPE is a structural-family parameter. Walls and floors
        /// carry a structural MATERIAL (an element id), not this enum, so a filter
        /// binding them to it cannot be created.
        /// </summary>
        private static readonly HashSet<string> MaterialTypeCategories = new HashSet<string>(StringComparer.Ordinal)
        {
            "OST_StructuralColumns", "OST_StructuralFraming", "OST_StructuralFoundation",
        };

        private static string RepoRoot()
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null && !File.Exists(Path.Combine(dir.FullName, "StingTools", "Data", "STING_AEC_FILTERS.json")))
                dir = dir.Parent;
            Assert.True(dir != null, "Could not locate StingTools/Data");
            return dir.FullName;
        }

        private static Dictionary<string, long> EnumValues()
        {
            var path = Path.Combine(RepoRoot(), "StingTools.Tags.Tests", "Fixtures", "RevitEnumValues.txt");
            return File.ReadAllLines(path)
                .Select(l => l.Trim())
                .Where(l => l.Length > 0 && !l.StartsWith("#"))
                .Select(l => l.Split('='))
                .ToDictionary(p => p[0], p => long.Parse(p[1]), StringComparer.Ordinal);
        }

        private static IEnumerable<(string Id, JArray Cats, JObject Leaf)> Leaves()
        {
            var root = JObject.Parse(File.ReadAllText(Path.Combine(RepoRoot(), "StingTools", "Data", "STING_AEC_FILTERS.json")));
            foreach (JObject f in root["filters"])
            {
                var stack = new Stack<JObject>();
                if (f["rule"] is JObject r0) stack.Push(r0);
                while (stack.Count > 0)
                {
                    var n = stack.Pop();
                    if (n["param"] != null) yield return ((string)f["id"], (JArray)f["categories"], n);
                    if (n["rules"] is JArray kids)
                        foreach (var k in kids.OfType<JObject>()) stack.Push(k);
                }
            }
        }

        [Fact]
        public void FixtureCarriesTheEnumsTheFiltersUse()
        {
            var values = EnumValues();
            foreach (var e in EnumParams.Values)
                Assert.True(values.Keys.Any(k => k.StartsWith(e + ".", StringComparison.Ordinal)),
                    $"RevitEnumValues.txt has no members of {e} — regenerate it with tools/DumpBuiltInParameterNames");
        }

        [Fact]
        public void EveryEnumValuedRuleNamesItsMemberAndTheIntegerMatchesRevit()
        {
            var values = EnumValues();
            var failures = new List<string>();
            int checkedRules = 0;
            foreach (var (id, _, leaf) in Leaves())
            {
                string param = (string)leaf["param"];
                if (param == null || !EnumParams.TryGetValue(param, out var expectedEnum)) continue;
                string op = ((string)leaf["op"] ?? "").ToLowerInvariant();
                if (op == "hasvalue" || op == "hasnovalue") continue;
                checkedRules++;

                string enumName = (string)leaf["enum"];
                string member = (string)leaf["valueName"];
                if (enumName != expectedEnum) { failures.Add($"{id}: {param} rule must declare \"enum\": \"{expectedEnum}\" (got '{enumName}')"); continue; }
                if (string.IsNullOrEmpty(member)) { failures.Add($"{id}: {param} rule has no \"valueName\""); continue; }
                if (!values.TryGetValue(enumName + "." + member, out var real)) { failures.Add($"{id}: {enumName}.{member} is not a Revit enum member"); continue; }
                if (!long.TryParse((string)leaf["value"], out var stated) || stated != real)
                    failures.Add($"{id}: {enumName}.{member} is {real} in Revit, the rule says '{leaf["value"]}'");
            }
            Assert.True(checkedRules > 0, "no enum-valued rules found — has the file moved?");
            Assert.True(failures.Count == 0, string.Join("\n", failures));
        }

        [Fact]
        public void StructuralMaterialTypeFiltersBindOnlyStructuralFamilyCategories()
        {
            var bad = Leaves()
                .Where(x => (string)x.Leaf["param"] == "STRUCTURAL_MATERIAL_TYPE")
                .SelectMany(x => x.Cats.Select(c => (x.Id, Cat: (string)c)))
                .Where(x => !MaterialTypeCategories.Contains(x.Cat))
                .Select(x => $"{x.Id}: {x.Cat}")
                .Distinct().ToList();
            Assert.True(bad.Count == 0, "STRUCTURAL_MATERIAL_TYPE bound to categories that do not carry it: " + string.Join(", ", bad));
        }
    }
}
