using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using StingTools.Core;
using Xunit;

namespace StingTools.Tags.Tests
{
    /// <summary>
    /// The per-token tag completeness policy.
    ///
    /// This file shipped from 2026-08-10 documenting all ten tokens, was named in two
    /// TagConfig comments, and was read by NOTHING — the fallbacks were hardcoded
    /// literals, so editing it changed no behaviour. These tests exist to keep it wired:
    /// the shipped baseline is parsed with the same POCO the plugin uses, and the
    /// substitution/refusal decisions are asserted directly.
    /// </summary>
    public class TagTokenPolicyTests
    {
        /// <summary>The seven segments of the ISO 19650 tag string. STATUS and REV are
        /// carried for lifecycle reporting and are not part of it; SEQ is generated by
        /// SeqAssigner and never reaches the policy.</summary>
        private static readonly string[] TagSegments =
            { "DISC", "LOC", "ZONE", "LVL", "SYS", "FUNC", "PROD" };

        private static string BaselinePath()
        {
            string p = Path.Combine(AppContext.BaseDirectory, "Data", TagTokenPolicy.BaselineFileName);
            if (!File.Exists(p))
                throw new FileNotFoundException(
                    "The shipped token policy was not copied to the test output. Without it every " +
                    "assertion below would pass on an empty library — which is precisely the state " +
                    "the plugin was in for a month. Check the <None Include> entry in " +
                    "StingTools.Tags.Tests.csproj.", p);
            return p;
        }

        private static TagTokenPolicyLibrary Baseline()
        {
            return TagTokenPolicy.Parse(File.ReadAllText(BaselinePath()));
        }

        // ── The shipped file ────────────────────────────────────────────────

        [Fact]
        public void The_shipped_baseline_binds_every_field_it_declares()
        {
            var warnings = new List<string>();
            var lib = TagTokenPolicy.Parse(File.ReadAllText(BaselinePath()), warnings);

            Assert.Equal(10, lib.Tokens.Count);
            Assert.Empty(warnings);   // no unrecognised level strings

            foreach (var t in lib.Tokens)
            {
                Assert.False(string.IsNullOrWhiteSpace(t.Token));
                Assert.False(string.IsNullOrWhiteSpace(t.Param),
                    t.Token + " has no param — the JSON key is probably misspelled.");
                Assert.False(string.IsNullOrWhiteSpace(t.Why),
                    t.Token + " has no rationale. Every level here is a judgement call.");

                // Level must PARSE, not merely be present: OPTIONAL is the enum's zero,
                // so a typo would silently downgrade a MANDATORY token to a silent blank.
                TagTokenLevel level;
                Assert.True(t.TryResolveLevel(out level),
                    t.Token + " has level '" + (t.Level ?? "(missing)") + "', which is not " +
                    "MANDATORY, DERIVED or OPTIONAL.");
            }
        }

        [Fact]
        public void The_shipped_baseline_can_never_refuse_to_tag_an_element()
        {
            // The refusal path is real and tested below, but turning it on is a PROJECT
            // decision. If a corporate edit ever drops a fallback from one of the seven
            // segments, every levelless (or discipline-less, or …) element in every
            // project silently stops being tagged. That must not happen by accident.
            var lib = Baseline();

            foreach (string token in TagSegments)
            {
                var res = TagTokenPolicy.Resolve(lib, token, "");
                Assert.False(res.Refused,
                    "Shipped baseline refuses on a blank " + token + ": " + res.Reason +
                    " Give it a fallback, or accept that every project stops tagging these.");
                Assert.False(string.IsNullOrEmpty(res.Value),
                    "Shipped baseline resolves a blank " + token + " to an empty string, which " +
                    "would emit a doubled separator in the tag.");
            }
        }

        [Fact]
        public void The_shipped_fallbacks_are_the_literals_the_hardcoded_block_used()
        {
            // Wiring the loader must not CHANGE any tag. These are the exact values
            // TagConfig.BuildAndWriteTag substituted before the policy governed anything;
            // if one of them moves, tags change project-wide and that must be deliberate.
            var lib = Baseline();
            var expected = new Dictionary<string, string>
            {
                { "DISC", "A" }, { "LOC", "BLD1" }, { "ZONE", "Z01" }, { "LVL", "L00" },
                { "SYS", "GEN" }, { "FUNC", "GEN" }, { "PROD", "GEN" },
            };

            foreach (var kv in expected)
                Assert.Equal(kv.Value, TagTokenPolicy.Resolve(lib, kv.Key, "").Value);
        }

        [Fact]
        public void Seq_has_no_fallback_because_there_is_no_defensible_one()
        {
            var seq = TagTokenPolicy.Find(Baseline(), "SEQ");

            Assert.NotNull(seq);
            TagTokenLevel level;
            Assert.True(seq.TryResolveLevel(out level));
            Assert.Equal(TagTokenLevel.Mandatory, level);
            Assert.Null(seq.Fallback);   // a tag ending in a bare separator is always wrong
        }

        [Fact]
        public void Status_and_rev_are_optional_and_stay_blank()
        {
            var lib = Baseline();

            foreach (string token in new[] { "STATUS", "REV" })
            {
                var res = TagTokenPolicy.Resolve(lib, token, "");
                Assert.Equal(TagTokenLevel.Optional, res.Level);
                Assert.False(res.Refused);
                Assert.False(res.Substituted);   // silent — blank is a real answer
                Assert.Equal("", res.Value);
            }
        }

        [Fact]
        public void The_file_claims_governance_only_for_the_tokens_that_are_actually_resolved()
        {
            // The policy file spent a month describing behaviour nothing implemented. The
            // same over-claim in miniature would be listing ten tokens as governed when
            // BuildAndWriteTag resolves seven. governedByResolve has to match TagSegments.
            var root = Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(BaselinePath()));
            var tokens = (Newtonsoft.Json.Linq.JArray)root["tokens"];

            var claimed = new List<string>();
            foreach (var t in tokens)
            {
                string name = (string)t["token"];
                string governed = (string)t["governedByResolve"];
                Assert.False(string.IsNullOrWhiteSpace(governed),
                    name + " does not say whether it is governed by TagTokenPolicy.Resolve.");
                if (governed == "yes") claimed.Add(name);
                else
                    Assert.False(string.IsNullOrWhiteSpace((string)t["governedNote"]),
                        name + " claims it is not governed but does not say why. A reader " +
                        "needs the reason, not the verdict.");
            }

            Assert.Equal(
                TagSegments.OrderBy(x => x, StringComparer.Ordinal).ToArray(),
                claimed.OrderBy(x => x, StringComparer.Ordinal).ToArray());
        }

        // ── Resolve ─────────────────────────────────────────────────────────

        [Fact]
        public void A_value_from_the_model_is_used_as_is_and_recorded_as_nothing()
        {
            var res = TagTokenPolicy.Resolve(Baseline(), "SYS", "HVAC");

            Assert.Equal("HVAC", res.Value);
            Assert.False(res.Substituted);
            Assert.False(res.Refused);
        }

        [Fact]
        public void A_substitution_is_recorded_rather_than_silent()
        {
            var res = TagTokenPolicy.Resolve(Baseline(), "SYS", "");

            Assert.Equal("GEN", res.Value);
            // The whole point: the caller can tell a measured GEN from an assumed one.
            Assert.True(res.Substituted);
            Assert.Equal(TagTokenLevel.Derived, res.Level);
        }

        [Fact]
        public void A_mandatory_substitution_is_distinguishable_from_a_derived_one()
        {
            var lib = Baseline();

            Assert.Equal(TagTokenLevel.Mandatory, TagTokenPolicy.Resolve(lib, "DISC", "").Level);
            Assert.Equal(TagTokenLevel.Derived, TagTokenPolicy.Resolve(lib, "SYS", "").Level);
        }

        [Fact]
        public void A_null_fallback_refuses_rather_than_guessing()
        {
            // What a project turns on when it would rather skip an element than tag it
            // with an assumed value.
            var project = TagTokenPolicy.Parse(
                "{ \"tokens\": [ { \"token\": \"LVL\", \"level\": \"MANDATORY\", \"fallback\": null, " +
                "\"why\": \"House rule: a levelless element is a modelling error.\" } ] }");
            var lib = TagTokenPolicy.Merge(Baseline(), project);

            var res = TagTokenPolicy.Resolve(lib, "LVL", "");

            Assert.True(res.Refused);
            Assert.Contains("House rule", res.Reason);
            // And it does not quietly hand back a value the caller might write anyway.
            Assert.Equal("", res.Value);
        }

        [Fact]
        public void An_unknown_token_falls_back_to_the_built_in_and_says_so()
        {
            // A policy file that forgets a token must not produce a doubled separator.
            // The safety net fires, and the Reason makes the gap visible.
            var res = TagTokenPolicy.Resolve(new TagTokenPolicyLibrary(), "PROD", "");

            Assert.Equal("GEN", res.Value);
            Assert.True(res.Substituted);
            Assert.False(res.Refused);
            Assert.Contains("not described by", res.Reason);
        }

        [Fact]
        public void A_token_with_neither_a_rule_nor_a_safety_net_is_refused()
        {
            var res = TagTokenPolicy.Resolve(new TagTokenPolicyLibrary(), "NOSUCHTOKEN", "");

            Assert.True(res.Refused);
            Assert.Equal("", res.Value);
        }

        [Fact]
        public void An_unrecognised_level_warns_and_is_treated_as_derived()
        {
            var warnings = new List<string>();
            var lib = TagTokenPolicy.Parse(
                "{ \"tokens\": [ { \"token\": \"SYS\", \"level\": \"MANDITORY\", \"fallback\": \"GEN\" } ] }",
                warnings);

            Assert.Single(warnings);
            Assert.Contains("MANDITORY", warnings[0]);
            // Treated as DERIVED, not as OPTIONAL — OPTIONAL is the enum's zero value and
            // would have silently turned a typo into "blank is fine".
            Assert.Equal(TagTokenLevel.Derived, TagTokenPolicy.Resolve(lib, "SYS", "").Level);
        }

        // ── Layering ────────────────────────────────────────────────────────

        [Fact]
        public void A_project_rule_replaces_the_baseline_rule_wholesale()
        {
            // The documented hospital case: ZONE is the fire compartment, so it is
            // mandatory and there is no safe default.
            var project = TagTokenPolicy.Parse(
                "{ \"tokens\": [ { \"token\": \"ZONE\", \"level\": \"MANDATORY\", \"fallback\": null, " +
                "\"why\": \"ZONE is the fire compartment.\" } ] }");
            var lib = TagTokenPolicy.Merge(Baseline(), project);

            Assert.Equal(10, lib.Tokens.Count);   // overridden, not appended

            var zone = TagTokenPolicy.Resolve(lib, "ZONE", "");
            Assert.True(zone.Refused);

            // And nothing else moved.
            Assert.Equal("GEN", TagTokenPolicy.Resolve(lib, "SYS", "").Value);
            Assert.Equal("A", TagTokenPolicy.Resolve(lib, "DISC", "").Value);
        }

        [Fact]
        public void A_project_can_relax_a_token_as_well_as_tighten_it()
        {
            var project = TagTokenPolicy.Parse(
                "{ \"tokens\": [ { \"token\": \"ZONE\", \"level\": \"OPTIONAL\", \"fallback\": null, " +
                "\"why\": \"Single-building lodge: there are no zones.\" } ] }");
            var lib = TagTokenPolicy.Merge(Baseline(), project);

            var res = TagTokenPolicy.Resolve(lib, "ZONE", "");
            Assert.False(res.Refused);
            Assert.False(res.Substituted);
            Assert.Equal("", res.Value);
        }

        [Fact]
        public void A_missing_project_file_leaves_the_baseline_intact()
        {
            var warnings = new List<string>();
            var project = TagTokenPolicy.LoadFile(
                Path.Combine(Path.GetTempPath(), "sting-no-such-token-policy.json"), warnings);

            Assert.Empty(project.Tokens);
            Assert.Empty(warnings);
            Assert.Equal(10, TagTokenPolicy.Merge(Baseline(), project).Tokens.Count);
        }

        [Fact]
        public void Malformed_project_json_warns_and_leaves_the_baseline_governing()
        {
            string path = Path.Combine(Path.GetTempPath(),
                "sting-broken-token-policy-" + Guid.NewGuid().ToString("N") + ".json");
            File.WriteAllText(path, "{ this is not json");
            try
            {
                var warnings = new List<string>();
                var project = TagTokenPolicy.LoadFile(path, warnings);

                Assert.Empty(project.Tokens);
                Assert.Single(warnings);

                // Tagging still works, on corporate rules.
                var lib = TagTokenPolicy.Merge(Baseline(), project);
                Assert.Equal("GEN", TagTokenPolicy.Resolve(lib, "SYS", "").Value);
            }
            finally { File.Delete(path); }
        }

        [Fact]
        public void An_empty_policy_still_tags_every_segment_via_the_safety_net()
        {
            // Worst case: the baseline is missing from the install and the project has no
            // override. Tagging must degrade to the old literals, not to doubled separators.
            var empty = new TagTokenPolicyLibrary();

            foreach (string token in TagSegments)
            {
                var res = TagTokenPolicy.Resolve(empty, token, "");
                Assert.False(res.Refused, token + " refused with no policy at all.");
                Assert.False(string.IsNullOrEmpty(res.Value));
            }
        }
    }
}
