// <auto-generated>
// GENERATED by /tmp/work/build_map_cs.py — do not hand-edit.
// Source of truth: TIER_VARIATION_MATRIX.md + task-brief Section 2.
// Regenerate with `python3 /tmp/work/build_map_cs.py`.
// </auto-generated>
using System.Collections.Generic;

namespace StingTools.Core
{
    /// <summary>Ternary state per paragraph tier (T4..T10).</summary>
    public enum TierState
    {
        /// <summary>Use the default 3-row block for this tier.</summary>
        Keep,
        /// <summary>Replace the default rows with a discipline-specific set (see Rows list for parameter names).</summary>
        Replace,
        /// <summary>Omit all rows for this tier AND drop the TAG_PARA_STATE_N_BOOL from VisibilityParams for this family.</summary>
        Omit,
    }

    /// <summary>One visible row inside a tier — parameter reference + affixes.</summary>
    public sealed class TierRow
    {
        public string Tier { get; set; }
        public string Parameter { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public int Spc { get; set; }
        public bool Brk { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
        public string Color { get; set; }
        public double Size { get; set; }
    }

    /// <summary>State + row list for every tier T4..T10 in a tag family.</summary>
    public sealed class TierPlan
    {
        public TierState T4 { get; set; } = TierState.Keep;
        public TierState T5 { get; set; } = TierState.Keep;
        public TierState T6 { get; set; } = TierState.Keep;
        public TierState T7 { get; set; } = TierState.Keep;
        public TierState T8 { get; set; } = TierState.Keep;
        public TierState T9 { get; set; } = TierState.Keep;
        public TierState T10 { get; set; } = TierState.Keep;
        public List<TierRow> T4Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T5Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T6Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T7Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T8Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T9Rows { get; set; } = new List<TierRow>();
        public List<TierRow> T10Rows { get; set; } = new List<TierRow>();

        /// <summary>True if the specified tier (4..10) is OMITted for this family.</summary>
        public bool IsOmitted(int tier)
        {
            switch (tier)
            {
                case 4: return T4 == TierState.Omit;
                case 5: return T5 == TierState.Omit;
                case 6: return T6 == TierState.Omit;
                case 7: return T7 == TierState.Omit;
                case 8: return T8 == TierState.Omit;
                case 9: return T9 == TierState.Omit;
                case 10: return T10 == TierState.Omit;
                default: return false;
            }
        }
    }

    /// <summary>
    /// Per-family T4..T10 tier policy. Consumed by TagFamilyCreatorCommand to filter
    /// VisibilityParams (dropping TAG_PARA_STATE_N_BOOL for OMITted tiers) and by the
    /// CSV regenerator to pick which rows to emit for each family.
    /// </summary>
    public static class PerFamilyTierMap
    {
        /// <summary>
        /// Narrative-only mode (opt-in). When true, Resolve() forces T4..T10
        /// to Omit on every plan so tag families drop those label rows and all
        /// T4-T10 content lives in ASS_TAG_7_TXT (composed by
        /// ApplyParagraphPresetCommand from PARAGRAPH_PRESETS.json).
        /// Default false — T4-T10 stay as real label rows so tags remain
        /// live-bound to source parameters (schedules, IFC/COBie export, and
        /// view filters all read the actual parameters). The Paragraph
        /// Builder, presets, and Tag 7 updater are still available as an
        /// additive surface for user-composed prose in ASS_TAG_7_TXT.
        /// </summary>
        public const bool NarrativeOnlyTiers4To10 = false;

        /// <summary>Default plan = all tiers KEEP (applies to unrecognised families).</summary>
        public static TierPlan DefaultPlan { get; } = ApplyNarrativeMode(new TierPlan());

        private static readonly Dictionary<string, TierPlan> ByFamilyName = BuildFamilyMap();
        private static readonly Dictionary<string, TierPlan> ByCategory = BuildCategoryMap();

        /// <summary>Resolve a plan for a tag family. Tries family name first, falls back to Revit category, then DefaultPlan.</summary>
        public static TierPlan Resolve(string familyName, string revitCategory)
        {
            TierPlan plan;
            if (!string.IsNullOrEmpty(familyName) && ByFamilyName.TryGetValue(familyName, out var p))
                plan = p;
            else if (!string.IsNullOrEmpty(revitCategory) && ByCategory.TryGetValue(revitCategory, out var q))
                plan = q;
            else
                plan = DefaultPlan;
            return ApplyNarrativeMode(plan);
        }

        /// <summary>
        /// Force every T4..T10 state on the supplied plan to Omit when
        /// NarrativeOnlyTiers4To10 is on, regardless of what the per-family
        /// matrix said. Leaves T1..T3 and the Rows lists untouched so legacy
        /// consumers that still inspect them do not crash.
        /// </summary>
        private static TierPlan ApplyNarrativeMode(TierPlan plan)
        {
            if (!NarrativeOnlyTiers4To10 || plan == null) return plan;
            plan.T4 = TierState.Omit;
            plan.T5 = TierState.Omit;
            plan.T6 = TierState.Omit;
            plan.T7 = TierState.Omit;
            plan.T8 = TierState.Omit;
            plan.T9 = TierState.Omit;
            plan.T10 = TierState.Omit;
            return plan;
        }

        /// <summary>Enumerate all known family names (for diagnostics and smoke tests).</summary>
        public static IEnumerable<string> KnownFamilyNames => ByFamilyName.Keys;

        // ----------------------------------------------------------------------
        // Helper factories
        // ----------------------------------------------------------------------
        private static TierPlan PhysicalDefault() => new TierPlan();

        private static TierPlan Spatial() => new TierPlan
        {
            T7 = TierState.Omit,
            T9 = TierState.Omit,
        };

        private static TierPlan Annotation() => new TierPlan
        {
            T4 = TierState.Omit,
            T6 = TierState.Omit,
            T7 = TierState.Omit,
            T8 = TierState.Omit,
            T9 = TierState.Omit,
            T10 = TierState.Omit,
        };

        private static List<TierRow> RowsForSet(string setId)
        {
            // Row data mirrors the rows the CSV regenerator emits. Used only for diagnostics;
            // TagFamilyCreatorCommand only reads TierState today.
            switch (setId)
            {
                case "STR_REBAR_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "STR_BAR_MARK_TXT", Prefix = "Mark:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Rebar - Bar Mark", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "STR_BEND_SCHEDULE_REF_TXT", Prefix = "BBS:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Rebar - BBS Ref", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "STR_CUTTING_LIST_REF_TXT", Prefix = "CL:", Suffix = "", Spc = 0, Brk = true, Name = "T7 - Rebar - Cutting List", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "STR_CONN_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "STR_WELD_PROCEDURE_REF_TXT", Prefix = "WPS:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Connection - WPS", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "STR_BOLT_TORQUE_NM_NR", Prefix = "Tq:", Suffix = "Nm", Spc = 1, Brk = false, Name = "T7 - Connection - Bolt Torque", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ASS_QC_INSPECTOR_TXT", Prefix = "QC:", Suffix = "", Spc = 0, Brk = true, Name = "T7 - Connection - QC Inspector", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "HVC_REFRIG_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "HVC_REFRIGERANT_CHARGE_KG_NR", Prefix = "R-chg:", Suffix = "kg", Spc = 1, Brk = false, Name = "T7 - Refrigerant Charge", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "HVC_FACTORY_FLASH_TEST_DATE_TXT", Prefix = "Flash:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Flash Test Date", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "HVC_FACTORY_QR_TXT", Prefix = "QR:", Suffix = "", Spc = 0, Brk = true, Name = "T7 - Factory QR", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "ELC_PANEL_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "ELC_PANEL_SCHEDULE_REF_TXT", Prefix = "PS:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Panel Schedule", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ELC_FAT_CERT_REF_TXT", Prefix = "FAT:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - FAT Cert", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ELC_FACTORY_QR_TXT", Prefix = "QR:", Suffix = "", Spc = 0, Brk = true, Name = "T7 - Elec Factory QR", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "PLM_PRESSURE_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "PLM_PRESSURE_TEST_REF_TXT", Prefix = "HT:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Hydrostatic Test", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "PLM_WELD_MAP_REF_TXT", Prefix = "WM:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Pipe Weld Map", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ASS_QC_INSPECTOR_TXT", Prefix = "QC:", Suffix = "", Spc = 0, Brk = true, Name = "T7 - Pipework QC", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "ARC_DOOR_WIN_T7":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T7", Parameter = "ARC_FACTORY_ORDER_REF_TXT", Prefix = "FO:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Factory Order", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ARC_GLAZING_SPEC_TXT", Prefix = "Glz:", Suffix = "", Spc = 0, Brk = false, Name = "T7 - Glazing Spec", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                        new TierRow { Tier = "T7", Parameter = "ASS_WARRANTY_DURATION_PARTS_YRS", Prefix = "Warr:", Suffix = "yr", Spc = 1, Brk = true, Name = "T7 - Warranty Parts", Style = "BOLD", Color = "ORANGE", Size = 2.0 },
                    };
                case "CBN_OPERATIONAL_T6":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T6", Parameter = "CBN_B6_KG_CO2E_YR", Prefix = "B6:", Suffix = "kgCO₂e/yr", Spc = 0, Brk = false, Name = "T6 - Operational B6", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                        new TierRow { Tier = "T6", Parameter = "CBN_A1_A3_KG_CO2E", Prefix = "| A1-A3:", Suffix = "kgCO₂e", Spc = 0, Brk = false, Name = "T6 - Product A1-A3", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                        new TierRow { Tier = "T6", Parameter = "CBN_RUNTIME_HRS_YR_NR", Prefix = "| Run:", Suffix = "hr/yr", Spc = 1, Brk = true, Name = "T6 - Runtime hrs/yr", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                    };
                case "CBN_REFRIG_T6":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T6", Parameter = "CBN_B6_KG_CO2E_YR", Prefix = "B6:", Suffix = "kgCO₂e/yr", Spc = 0, Brk = false, Name = "T6 - Operational B6", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                        new TierRow { Tier = "T6", Parameter = "CBN_A1_A3_KG_CO2E", Prefix = "| A1-A3:", Suffix = "kgCO₂e", Spc = 0, Brk = false, Name = "T6 - Product A1-A3", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                        new TierRow { Tier = "T6", Parameter = "CBN_RUNTIME_HRS_YR_NR", Prefix = "| Run:", Suffix = "hr/yr", Spc = 1, Brk = false, Name = "T6 - Runtime hrs/yr", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                        new TierRow { Tier = "T6", Parameter = "CBN_REFRIGERANT_GWP_KG_CO2E", Prefix = "| GWP:", Suffix = "kgCO₂e", Spc = 1, Brk = true, Name = "T6 - Refrigerant GWP", Style = "ITALIC", Color = "GREEN", Size = 2.0 },
                    };
                case "ASBUILT_REBAR_T9":
                    return new List<TierRow>
                    {
                        new TierRow { Tier = "T9", Parameter = "ASBUILT_COVER_DEVIATION_MM", Prefix = "ΔCvr:", Suffix = "mm", Spc = 1, Brk = false, Name = "T9 - Cover Deviation", Style = "ITALIC", Color = "GREY", Size = 2.0 },
                        new TierRow { Tier = "T9", Parameter = "ASBUILT_CAPTURE_DATE_TXT", Prefix = "on", Suffix = "", Spc = 0, Brk = false, Name = "T9 - Capture Date", Style = "ITALIC", Color = "GREY", Size = 2.0 },
                        new TierRow { Tier = "T9", Parameter = "HEALTH_SCORE_LAST_NR", Prefix = "Health:", Suffix = "/100", Spc = 1, Brk = true, Name = "T9 - Health Score", Style = "ITALIC", Color = "GREY", Size = 2.0 },
                    };
                default:
                    return new List<TierRow>();
            }
        }

        private static TierPlan PhysicalWithReplace(IDictionary<string, string> replacements)
        {
            var plan = PhysicalDefault();
            foreach (var kv in replacements)
            {
                switch (kv.Key)
                {
                    case "T4": plan.T4 = TierState.Replace; plan.T4Rows = RowsForSet(kv.Value); break;
                    case "T5": plan.T5 = TierState.Replace; plan.T5Rows = RowsForSet(kv.Value); break;
                    case "T6": plan.T6 = TierState.Replace; plan.T6Rows = RowsForSet(kv.Value); break;
                    case "T7": plan.T7 = TierState.Replace; plan.T7Rows = RowsForSet(kv.Value); break;
                    case "T8": plan.T8 = TierState.Replace; plan.T8Rows = RowsForSet(kv.Value); break;
                    case "T9": plan.T9 = TierState.Replace; plan.T9Rows = RowsForSet(kv.Value); break;
                    case "T10": plan.T10 = TierState.Replace; plan.T10Rows = RowsForSet(kv.Value); break;
                }
            }
            return plan;
        }

        private static Dictionary<string, TierPlan> BuildFamilyMap()
        {
            var d = new Dictionary<string, TierPlan>();
            d["STING - Wall Tag"] = PhysicalDefault();
            d["STING - Floor Tag"] = PhysicalDefault();
            d["STING - Ceiling Tag"] = PhysicalDefault();
            d["STING - Roof Tag"] = PhysicalDefault();
            d["STING - Door Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "ARC_DOOR_WIN_T7" } });
            d["STING - Window Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "ARC_DOOR_WIN_T7" } });
            d["STING - Room Tag"] = Spatial();
            d["STING - Stair Tag"] = PhysicalDefault();
            d["STING - Ramp Tag"] = PhysicalDefault();
            d["STING - Railing Tag"] = PhysicalDefault();
            d["STING - Furniture Tag"] = PhysicalDefault();
            d["STING - Casework Tag"] = PhysicalDefault();
            d["STING - Curtain Panel Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "ARC_DOOR_WIN_T7" } });
            d["STING - Curtain Wall Mullion Tag"] = PhysicalDefault();
            d["STING - Signage Tag"] = PhysicalDefault();
            d["STING - Parking Tag"] = PhysicalDefault();
            d["STING - Areas Tag"] = Spatial();
            d["STING - Wall Sweeps Tag"] = PhysicalDefault();
            d["STING - Slab Edges Tag"] = PhysicalDefault();
            d["STING - Roof Soffits Tag"] = PhysicalDefault();
            d["STING - Fascia Tag"] = PhysicalDefault();
            d["STING - Gutter Tag"] = PhysicalDefault();
            d["STING - Mass Tag"] = PhysicalDefault();
            d["STING - Furniture Systems Tag"] = PhysicalDefault();
            d["STING - Food Service Equipment Tag"] = PhysicalDefault();
            d["STING - Medical Equipment Tag"] = PhysicalDefault();
            d["STING - Entourage Tag"] = PhysicalDefault();
            d["STING - Stair Runs Tag"] = PhysicalDefault();
            d["STING - Stair Landings Tag"] = PhysicalDefault();
            d["STING - Stair Supports Tag"] = PhysicalDefault();
            d["STING - Top Rails Tag"] = PhysicalDefault();
            d["STING - Handrails Tag"] = PhysicalDefault();
            d["STING - Vertical Circulation Tag"] = PhysicalDefault();
            d["STING - Architectural Sheet Tag"] = Annotation();
            d["STING - Architectural Column Tag"] = PhysicalDefault();
            d["STING - Generic Models Tag"] = PhysicalDefault();
            d["STING - Specialty Equipment Tag"] = PhysicalDefault();
            d["STING - Site Tag"] = PhysicalDefault();
            d["STING - Planting Tag"] = PhysicalDefault();
            d["STING - Hardscape Tag"] = PhysicalDefault();
            d["STING - Roads Tag"] = PhysicalDefault();
            d["STING - Pads Tag"] = PhysicalDefault();
            d["STING - Toposolid Tag"] = PhysicalDefault();
            d["STING - Parts Tag"] = Spatial();
            d["STING - Assemblies Tag"] = Spatial();
            d["STING - Detail Items Tag"] = PhysicalDefault();
            d["STING - Profiles Tag"] = PhysicalDefault();
            d["STING - Materials Tag"] = PhysicalDefault();
            d["STING - Point Loads Tag"] = Spatial();
            d["STING - Line Loads Tag"] = Spatial();
            d["STING - Area Loads Tag"] = Spatial();
            d["STING - Internal Point Loads Tag"] = Spatial();
            d["STING - Internal Line Loads Tag"] = Spatial();
            d["STING - Internal Area Loads Tag"] = Spatial();
            d["STING - Analytical Members Tag"] = Spatial();
            d["STING - Analytical Nodes Tag"] = Spatial();
            d["STING - Analytical Panels Tag"] = Spatial();
            d["STING - Analytical Openings Tag"] = Spatial();
            d["STING - Analytical Links Tag"] = Spatial();
            d["STING - Model Groups Tag"] = Spatial();
            d["STING - RVT Links Tag"] = Spatial();
            d["STING - Property Lines Tag"] = Spatial();
            d["STING - Property Line Segments Tag"] = Spatial();
            d["STING - Bolt Tag"] = PhysicalDefault();
            d["STING - Toposolid Links Tag"] = Spatial();
            d["STING - Weld Tag"] = PhysicalDefault();
            d["STING - Wire Tag"] = PhysicalDefault();
            d["STING - Sheet Document Tag"] = Annotation();
            d["STING - Air Terminal Tag"] = PhysicalDefault();
            d["STING - Duct Accessory Tag"] = PhysicalDefault();
            d["STING - Duct Fitting Tag"] = PhysicalDefault();
            d["STING - Duct Tag"] = PhysicalDefault();
            d["STING - Flex Duct Tag"] = PhysicalDefault();
            d["STING - Mechanical Equipment Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_REFRIG_T6" }, { "T7", "HVC_REFRIG_T7" } });
            d["STING - Flex Pipe Tag"] = PhysicalDefault();
            d["STING - Pipe Accessory Tag"] = PhysicalDefault();
            d["STING - Pipe Fitting Tag"] = PhysicalDefault();
            d["STING - Pipe Tag"] = PhysicalDefault();
            d["STING - Plumbing Fixture Tag"] = PhysicalDefault();
            d["STING - Fire Alarm Device Tag"] = PhysicalDefault();
            d["STING - Sprinkler Tag"] = PhysicalDefault();
            d["STING - Cable Tray Fitting Tag"] = PhysicalDefault();
            d["STING - Cable Tray Tag"] = PhysicalDefault();
            d["STING - Conduit Fitting Tag"] = PhysicalDefault();
            d["STING - Conduit Tag"] = PhysicalDefault();
            d["STING - Electrical Equipment Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" }, { "T7", "ELC_PANEL_T7" } });
            d["STING - Electrical Fixture Tag"] = PhysicalDefault();
            d["STING - Lighting Device Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" } });
            d["STING - Lighting Fixture Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" } });
            d["STING - Communication Device Tag"] = PhysicalDefault();
            d["STING - Data Device Tag"] = PhysicalDefault();
            d["STING - Nurse Call Device Tag"] = PhysicalDefault();
            d["STING - Security Device Tag"] = PhysicalDefault();
            d["STING - Telephone Devices Tag"] = PhysicalDefault();
            d["STING - Generic Model Tag"] = PhysicalDefault();
            d["STING - Specialty Equipment Tag"] = PhysicalDefault();
            d["STING - Duct Insulation Tag"] = PhysicalDefault();
            d["STING - Duct Lining Tag"] = PhysicalDefault();
            d["STING - Pipe Insulation Tag"] = PhysicalDefault();
            d["STING - Plumbing Equipment Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "PLM_PRESSURE_T7" } });
            d["STING - Mechanical Control Devices Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" } });
            d["STING - Mechanical Equipment Sets Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_REFRIG_T6" }, { "T7", "HVC_REFRIG_T7" } });
            d["STING - Electrical Connectors Tag"] = PhysicalDefault();
            d["STING - Fire Protection Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" } });
            d["STING - MEP Fabrication Containment Tag"] = PhysicalDefault();
            d["STING - MEP Fabrication Ductwork Tag"] = PhysicalDefault();
            d["STING - MEP Fabrication Ductwork Stiffeners Tag"] = PhysicalDefault();
            d["STING - MEP Fabrication Hangers Tag"] = PhysicalDefault();
            d["STING - MEP Fabrication Pipework Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "PLM_PRESSURE_T7" } });
            d["STING - Materials Tag"] = PhysicalDefault();
            d["STING - Audio Visual Devices Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T6", "CBN_OPERATIONAL_T6" } });
            d["STING - Spaces Tag"] = Spatial();
            d["STING - Zones Tag"] = Spatial();
            d["STING - Tie-In Point Tag (Pipe — Plumbing & Hydraulic)"] = PhysicalDefault();
            d["STING - Tie-In Point Tag (Duct — HVAC)"] = PhysicalDefault();
            d["STING - Tie-In Point Tag (Conduit — Electrical LV/ELV)"] = PhysicalDefault();
            d["STING - Tie-In Point Tag (Cable Tray — Electrical)"] = PhysicalDefault();
            d["STING - Tie-In Point Tag (Fire Protection — Sprinkler / Suppression)"] = PhysicalDefault();
            d["STING - Tie-In Point Tag (Gas — Medical / Industrial / Natural Gas)"] = PhysicalDefault();
            d["STING - MEP Sheet Tag"] = Annotation();
            d["STING - MEP Sleeve Tag"] = PhysicalDefault();
            d["STING - Structural Column Tag"] = PhysicalDefault();
            d["STING - Structural Framing Tag"] = PhysicalDefault();
            d["STING - Structural Foundation Tag"] = PhysicalDefault();
            d["STING - Structural Slab Tag"] = PhysicalDefault();
            d["STING - Structural Wall Tag"] = PhysicalDefault();
            d["STING - Brace / Truss Tag"] = PhysicalDefault();
            d["STING - Structural Rebar Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_REBAR_T7" }, { "T9", "ASBUILT_REBAR_T9" } });
            d["STING - Structural Connection Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_CONN_T7" } });
            d["STING - Columns Tag"] = PhysicalDefault();
            d["STING - Structural Trusses Tag"] = PhysicalDefault();
            d["STING - Structural Stiffeners Tag"] = PhysicalDefault();
            d["STING - Structural Beam Systems Tag"] = PhysicalDefault();
            d["STING - Structural Rebar Couplers Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_REBAR_T7" }, { "T9", "ASBUILT_REBAR_T9" } });
            d["STING - Structural Fabric Reinforcement Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_REBAR_T7" }, { "T9", "ASBUILT_REBAR_T9" } });
            d["STING - Structural Area Reinforcement Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_REBAR_T7" }, { "T9", "ASBUILT_REBAR_T9" } });
            d["STING - Structural Path Reinforcement Tag"] = PhysicalWithReplace(new Dictionary<string, string> { { "T7", "STR_REBAR_T7" }, { "T9", "ASBUILT_REBAR_T9" } });
            d["STING - Internal Point Loads Tag"] = Spatial();
            d["STING - Internal Line Loads Tag"] = Spatial();
            d["STING - Internal Area Loads Tag"] = Spatial();
            d["STING - Analytical Members Tag"] = Spatial();
            d["STING - Structural Sheet Tag"] = Annotation();
            return d;
        }

        private static Dictionary<string, TierPlan> BuildCategoryMap()
        {
            // Category fallback for the spatial/annotation classes. Physical families
            // have too many category-specific REPLACE rules to safely key on category,
            // so they fall through to DefaultPlan when family-name lookup misses.
            var d = new Dictionary<string, TierPlan>();
            d["Analytical Links"] = Spatial();
            d["Analytical Members"] = Spatial();
            d["Analytical Nodes"] = Spatial();
            d["Analytical Openings"] = Spatial();
            d["Analytical Panels"] = Spatial();
            d["Area Loads"] = Spatial();
            d["Areas"] = Spatial();
            d["Assemblies"] = Spatial();
            d["Internal Area Loads"] = Spatial();
            d["Internal Line Loads"] = Spatial();
            d["Internal Point Loads"] = Spatial();
            d["Line Loads"] = Spatial();
            d["Model Groups"] = Spatial();
            d["Parts"] = Spatial();
            d["Point Loads"] = Spatial();
            d["Property Line Segments"] = Spatial();
            d["Property Lines"] = Spatial();
            d["RVT Links"] = Spatial();
            d["Rooms"] = Spatial();
            d["Spaces (MEP)"] = Spatial();
            d["Toposolid Links"] = Spatial();
            d["Zones (HVAC)"] = Spatial();
            d["Sheets (ViewSheet)"] = Annotation();
            d["Sheets — Architectural discipline"] = Annotation();
            d["Sheets — MEP disciplines (M/E/P/FP/LV)"] = Annotation();
            d["Sheets — Structural discipline"] = Annotation();
            return d;
        }
    }
}
