// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planscape.Infrastructure.Data;

#nullable disable

namespace Planscape.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PlanscapeDbContext))]
    partial class PlanscapeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .UseIdentityByDefaultColumns();

            modelBuilder.Entity("Planscape.Core.Entities.AuditLog", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("DetailsJson")
                    .HasColumnType("text");

                b.Property<string>("EntityId")
                    .HasColumnType("text");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("IpAddress")
                    .HasColumnType("text");

                b.Property<Guid?>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("Timestamp")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "Timestamp");

                b.HasIndex("TenantId", "Timestamp");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("Planscape.Core.Entities.AppUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("Iso19650Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RefreshToken")
                    .HasColumnType("text");

                b.Property<DateTime?>("RefreshTokenExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Role")
                    .HasColumnType("integer");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("TenantId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Planscape.Core.Entities.BimIssue", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Assignee")
                    .HasColumnType("text");

                b.Property<string>("BcfGuid")
                    .HasColumnType("text");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<string>("Discipline")
                    .HasColumnType("text");

                b.Property<DateTime?>("DueDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("IssueCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("LinkedElementIds")
                    .HasColumnType("text");

                b.Property<string>("Priority")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<DateTime?>("ResolvedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Revision")
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("DueDate")
                    .HasFilter("\"Status\" NOT IN ('CLOSED','RESOLVED')");

                b.HasIndex("ProjectId", "IssueCode")
                    .IsUnique();

                b.HasIndex("ProjectId", "Status");

                b.ToTable("Issues");
            });

            modelBuilder.Entity("Planscape.Core.Entities.ComplianceSnapshot", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ByDisciplineJson")
                    .HasColumnType("text");

                b.Property<string>("ByPhaseJson")
                    .HasColumnType("text");

                b.Property<string>("CapturedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CapturedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<double>("ContainerPercent")
                    .HasColumnType("double precision");

                b.Property<string>("EmptyTokenCountsJson")
                    .HasColumnType("text");

                b.Property<int>("FullyResolved")
                    .HasColumnType("integer");

                b.Property<int>("PlaceholderCount")
                    .HasColumnType("integer");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("RagStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("StaleCount")
                    .HasColumnType("integer");

                b.Property<double>("StrictPercent")
                    .HasColumnType("double precision");

                b.Property<int>("TaggedComplete")
                    .HasColumnType("integer");

                b.Property<int>("TaggedIncomplete")
                    .HasColumnType("integer");

                b.Property<double>("TagPercent")
                    .HasColumnType("double precision");

                b.Property<int>("TotalElements")
                    .HasColumnType("integer");

                b.Property<int>("Untagged")
                    .HasColumnType("integer");

                b.Property<int>("WarningCount")
                    .HasColumnType("integer");

                b.Property<int>("WarningHealthScore")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "CapturedAt");

                b.ToTable("ComplianceSnapshots");
            });

            modelBuilder.Entity("Planscape.Core.Entities.DevicePushToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DeviceName")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTime>("LastUsedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Platform")
                    .HasColumnType("integer");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("TenantId");

                b.HasIndex("UserId", "Token")
                    .IsUnique();

                b.ToTable("DevicePushTokens");
            });

            modelBuilder.Entity("Planscape.Core.Entities.IssueAttachment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("AttachedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("AttachedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid>("IssueId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("DocumentId");

                b.HasIndex("IssueId", "DocumentId")
                    .IsUnique();

                b.ToTable("IssueAttachments");
            });

            modelBuilder.Entity("Planscape.Core.Entities.DocumentRecord", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CdeStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ContentHash")
                    .HasColumnType("text");

                b.Property<string>("Description")
                    .HasMaxLength(1000)
                    .HasColumnType("character varying(1000)");

                b.Property<string>("Discipline")
                    .HasColumnType("text");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FilePath")
                    .HasColumnType("text");

                b.Property<long>("FileSizeBytes")
                    .HasColumnType("bigint");

                b.Property<string>("Originator")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("Revision")
                    .HasColumnType("text");

                b.Property<string>("StatusHistoryJson")
                    .HasColumnType("text");

                b.Property<string>("SuitabilityCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UploadedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "CdeStatus");

                b.HasIndex("ProjectId", "Discipline");

                b.HasIndex("ProjectId", "UploadedAt");

                b.ToTable("Documents");
            });

            modelBuilder.Entity("Planscape.Core.Entities.LicenseKey", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ActivatedMachineIds")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("CurrentActivations")
                    .HasColumnType("integer");

                b.Property<DateTime?>("ExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("LastActivatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LastActivatedBy")
                    .HasColumnType("text");

                b.Property<int>("MaxActivations")
                    .HasColumnType("integer");

                b.Property<bool>("MimEnabled")
                    .HasColumnType("boolean");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<int>("Tier")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Key")
                    .IsUnique();

                b.HasIndex("TenantId");

                b.ToTable("LicenseKeys");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Meeting", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("AgendaJson")
                    .HasColumnType("text");

                b.Property<string>("AttendeesJson")
                    .HasColumnType("text");

                b.Property<string>("CreatedAt")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("MeetingType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Minutes")
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("ScheduledAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "ScheduledAt");

                b.ToTable("Meetings");
            });

            modelBuilder.Entity("Planscape.Core.Entities.MeetingActionItem", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Assignee")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("DueDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("LinkedIssueId")
                    .HasColumnType("text");

                b.Property<Guid>("MeetingId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("MeetingId");

                b.ToTable("MeetingActionItems");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Project", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<double>("CompliancePercent")
                    .HasColumnType("double precision");

                b.Property<string>("ConfigJson")
                    .HasColumnType("text");

                b.Property<double>("ContainerCompliancePercent")
                    .HasColumnType("double precision");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<DateTime?>("LastSyncAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Phase")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RagStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("SeqNumPad")
                    .HasColumnType("integer");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<int>("TaggedElements")
                    .HasColumnType("integer");

                b.Property<string>("TagPrefix")
                    .HasColumnType("text");

                b.Property<string>("TagSeparator")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TagSuffix")
                    .HasColumnType("text");

                b.Property<Guid>("TenantId")
                    .HasColumnType("uuid");

                b.Property<int>("TotalElements")
                    .HasColumnType("integer");

                b.Property<int>("WarningCount")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("TenantId", "Code")
                    .IsUnique();

                b.ToTable("Projects");
            });

            modelBuilder.Entity("Planscape.Core.Entities.ProjectMember", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("InvitedBy")
                    .HasColumnType("text");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("Iso19650Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("JoinedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("ProjectRole")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "UserId")
                    .IsUnique();

                b.ToTable("ProjectMembers");
            });

            modelBuilder.Entity("Planscape.Core.Entities.SeqCounter", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CounterKey")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("CurrentValue")
                    .HasColumnType("integer");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UpdatedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "CounterKey")
                    .IsUnique();

                b.ToTable("SeqCounters");
            });

            modelBuilder.Entity("Planscape.Core.Entities.TaggedElement", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("CategoryName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Disc")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FamilyName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Func")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("GridRef")
                    .HasColumnType("text");

                b.Property<bool>("IsComplete")
                    .HasColumnType("boolean");

                b.Property<bool>("IsFullyResolved")
                    .HasColumnType("boolean");

                b.Property<bool>("IsStale")
                    .HasColumnType("boolean");

                b.Property<string>("Level")
                    .HasColumnType("text");

                b.Property<string>("Loc")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Lvl")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PreviousTag")
                    .HasColumnType("text");

                b.Property<string>("Prod")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("Rev")
                    .HasColumnType("text");

                b.Property<long>("RevitElementId")
                    .HasColumnType("bigint");

                b.Property<string>("RoomName")
                    .HasColumnType("text");

                b.Property<string>("Seq")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .HasColumnType("text");

                b.Property<DateTime>("SyncedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("SyncedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Sys")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Tag1")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Tag7")
                    .HasColumnType("text");

                b.Property<string>("Tag7A")
                    .HasColumnType("text");

                b.Property<string>("Tag7B")
                    .HasColumnType("text");

                b.Property<string>("Tag7C")
                    .HasColumnType("text");

                b.Property<string>("Tag7D")
                    .HasColumnType("text");

                b.Property<string>("Tag7E")
                    .HasColumnType("text");

                b.Property<string>("Tag7F")
                    .HasColumnType("text");

                b.Property<DateTime?>("TagModifiedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("TypeName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("UniqueId")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("ValidationErrors")
                    .HasColumnType("text");

                b.Property<string>("Zone")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("Disc");

                b.HasIndex("IsStale");

                b.HasIndex("Tag1");

                b.HasIndex("ProjectId", "RevitElementId")
                    .IsUnique();

                b.ToTable("TaggedElements");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ContactEmail")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<int>("MaxProjects")
                    .HasColumnType("integer");

                b.Property<int>("MaxUsers")
                    .HasColumnType("integer");

                b.Property<bool>("MimEnabled")
                    .HasColumnType("boolean");

                b.Property<int>("MimTier")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<long>("StorageLimitBytes")
                    .HasColumnType("bigint");

                b.Property<string>("StripeCustomerId")
                    .HasColumnType("text");

                b.Property<string>("StripeSubscriptionId")
                    .HasColumnType("text");

                b.Property<int>("Tier")
                    .HasColumnType("integer");

                b.Property<DateTime?>("TrialExpiresAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("Slug")
                    .IsUnique();

                b.ToTable("Tenants");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Transmittal", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("DocumentIdsJson")
                    .HasColumnType("text");

                b.Property<string>("Notes")
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("Recipient")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("SentAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TransmittalCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "TransmittalCode")
                    .IsUnique();

                b.ToTable("Transmittals");
            });

            modelBuilder.Entity("Planscape.Core.Entities.WorkflowRun", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<double>("ComplianceAfter")
                    .HasColumnType("double precision");

                b.Property<double>("ComplianceBefore")
                    .HasColumnType("double precision");

                b.Property<double>("DurationMs")
                    .HasColumnType("double precision");

                b.Property<DateTime>("ExecutedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("PresetName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<string>("StepResultsJson")
                    .HasColumnType("text");

                b.Property<int>("StepsFailed")
                    .HasColumnType("integer");

                b.Property<int>("StepsPassed")
                    .HasColumnType("integer");

                b.Property<int>("StepsSkipped")
                    .HasColumnType("integer");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ProjectId");

                b.ToTable("WorkflowRuns");
            });

            modelBuilder.Entity("Planscape.MIM.Entities.Asset", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal?>("AnnualMaintenanceCost")
                    .HasColumnType("numeric");

                b.Property<string>("AssetName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("AssetTag")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("BarCode")
                    .HasColumnType("text");

                b.Property<string>("Building")
                    .HasColumnType("text");

                b.Property<decimal?>("CapitalCost")
                    .HasColumnType("numeric");

                b.Property<string>("CategoryName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("CobieSpace")
                    .HasColumnType("text");

                b.Property<string>("CobieType")
                    .HasColumnType("text");

                b.Property<DateTime?>("CommissioningDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ConditionGrade")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<double?>("ConditionScore")
                    .HasColumnType("double precision");

                b.Property<string>("CostCurrency")
                    .HasColumnType("text");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DigitalTwinId")
                    .HasColumnType("text");

                b.Property<string>("Discipline")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("DocumentRefsJson")
                    .HasColumnType("text");

                b.Property<double?>("EmbodiedCarbonKgCo2")
                    .HasColumnType("double precision");

                b.Property<double?>("EnergyConsumptionKwh")
                    .HasColumnType("double precision");

                b.Property<int?>("ExpectedLifeYears")
                    .HasColumnType("integer");

                b.Property<DateTime?>("ExpectedReplacementDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("FamilyName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Floor")
                    .HasColumnType("text");

                b.Property<string>("FunctionCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("InstallationDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime?>("LastSensorReading")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Level")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("LifecycleStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Manufacturer")
                    .HasColumnType("text");

                b.Property<string>("ModelNumber")
                    .HasColumnType("text");

                b.Property<string>("OmniClassCode")
                    .HasColumnType("text");

                b.Property<string>("ProductCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ProjectId")
                    .HasColumnType("uuid");

                b.Property<decimal?>("ReplacementCost")
                    .HasColumnType("numeric");

                b.Property<string>("Room")
                    .HasColumnType("text");

                b.Property<string>("SensorDataJson")
                    .HasColumnType("text");

                b.Property<string>("SensorId")
                    .HasColumnType("text");

                b.Property<string>("SerialNumber")
                    .HasColumnType("text");

                b.Property<string>("SparePartsJson")
                    .HasColumnType("text");

                b.Property<string>("CriticalityRating")
                    .HasColumnType("text");

                b.Property<string>("SystemCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("TaggedElementId")
                    .HasColumnType("uuid");

                b.Property<string>("UniclassCode")
                    .HasColumnType("text");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int?>("WarrantyDurationMonths")
                    .HasColumnType("integer");

                b.Property<DateTime?>("WarrantyEnd")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("WarrantyProvider")
                    .HasColumnType("text");

                b.Property<DateTime?>("WarrantyStart")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Zone")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("ProjectId", "AssetTag")
                    .IsUnique();

                b.ToTable("Assets");
            });

            modelBuilder.Entity("Planscape.MIM.Entities.MaintenanceTask", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal?>("ActualCost")
                    .HasColumnType("numeric");

                b.Property<double?>("ActualHours")
                    .HasColumnType("double precision");

                b.Property<Guid>("AssetId")
                    .HasColumnType("uuid");

                b.Property<string>("AssignedTo")
                    .HasColumnType("text");

                b.Property<DateTime?>("CompletedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<decimal?>("EstimatedCost")
                    .HasColumnType("numeric");

                b.Property<double?>("EstimatedHours")
                    .HasColumnType("double precision");

                b.Property<int>("FrequencyDays")
                    .HasColumnType("integer");

                b.Property<bool>("IsStatutory")
                    .HasColumnType("boolean");

                b.Property<DateTime?>("NextDueDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Priority")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RegulatoryBody")
                    .HasColumnType("text");

                b.Property<DateTime?>("ScheduledDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("StandardReference")
                    .HasColumnType("text");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TaskCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AssetId");

                b.ToTable("MaintenanceTasks");
            });

            // ── Relationships ──

            modelBuilder.Entity("Planscape.Core.Entities.AppUser", b =>
            {
                b.HasOne("Planscape.Core.Entities.Tenant", "Tenant")
                    .WithMany("Users")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tenant");
            });

            modelBuilder.Entity("Planscape.Core.Entities.BimIssue", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany("Issues")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.ComplianceSnapshot", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.DevicePushToken", b =>
            {
                b.HasOne("Planscape.Core.Entities.Tenant", "Tenant")
                    .WithMany()
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Planscape.Core.Entities.AppUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tenant");

                b.Navigation("User");
            });

            modelBuilder.Entity("Planscape.Core.Entities.IssueAttachment", b =>
            {
                b.HasOne("Planscape.Core.Entities.DocumentRecord", "Document")
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Planscape.Core.Entities.BimIssue", "Issue")
                    .WithMany("Attachments")
                    .HasForeignKey("IssueId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Document");

                b.Navigation("Issue");
            });

            modelBuilder.Entity("Planscape.Core.Entities.DocumentRecord", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany("Documents")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.LicenseKey", b =>
            {
                b.HasOne("Planscape.Core.Entities.Tenant", "Tenant")
                    .WithMany("LicenseKeys")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tenant");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Meeting", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.MeetingActionItem", b =>
            {
                b.HasOne("Planscape.Core.Entities.Meeting", "Meeting")
                    .WithMany("ActionItems")
                    .HasForeignKey("MeetingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Meeting");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Project", b =>
            {
                b.HasOne("Planscape.Core.Entities.Tenant", "Tenant")
                    .WithMany("Projects")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Tenant");
            });

            modelBuilder.Entity("Planscape.Core.Entities.ProjectMember", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Planscape.Core.Entities.AppUser", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");

                b.Navigation("User");
            });

            modelBuilder.Entity("Planscape.Core.Entities.SeqCounter", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.TaggedElement", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany("Elements")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Transmittal", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.Core.Entities.WorkflowRun", b =>
            {
                b.HasOne("Planscape.Core.Entities.Project", "Project")
                    .WithMany("WorkflowRuns")
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Project");
            });

            modelBuilder.Entity("Planscape.MIM.Entities.MaintenanceTask", b =>
            {
                b.HasOne("Planscape.MIM.Entities.Asset", "Asset")
                    .WithMany("MaintenanceTasks")
                    .HasForeignKey("AssetId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Asset");
            });

            // ── Collection navigations ──

            modelBuilder.Entity("Planscape.Core.Entities.BimIssue", b =>
            {
                b.Navigation("Attachments");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Meeting", b =>
            {
                b.Navigation("ActionItems");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Project", b =>
            {
                b.Navigation("Documents");
                b.Navigation("Elements");
                b.Navigation("Issues");
                b.Navigation("WorkflowRuns");
            });

            modelBuilder.Entity("Planscape.Core.Entities.Tenant", b =>
            {
                b.Navigation("LicenseKeys");
                b.Navigation("Projects");
                b.Navigation("Users");
            });

            modelBuilder.Entity("Planscape.MIM.Entities.Asset", b =>
            {
                b.Navigation("MaintenanceTasks");
            });

#pragma warning restore 612, 618
        }
    }
}
