using System;
using System.Collections.Generic;
using System.Linq;
using Autodesk.Revit.DB;
using StingTools.Core.Symbols;
using StingTools.Tags;

namespace StingTools.Core.Drawing
{
    /// <summary>
    /// W1/W2 — shared discipline symbol-legend builder.
    ///
    /// Factored out of <c>ElectricalDrawingLegendCommand</c> so the exact same
    /// engine drives (a) the standalone Mechanical / Plumbing / Structural
    /// legend commands and (b) the <see cref="DrawingProducer"/> Legend
    /// production path (a Legend-purpose DrawingType now mints a populated
    /// legend instead of falling through to a FloorPlan).
    ///
    /// Strategy mirrors the electrical legend: walk every family instance in a
    /// discipline's categories, dedupe by (category, family, type), resolve
    /// each to its STING symbol concept via <see cref="SymbolConceptRegistry"/>,
    /// and render one row per unique symbol through the Phase 92
    /// <see cref="LegendBuilder"/> engine. When a discipline has no placed
    /// components (or the discipline is General "G"), it falls back to a
    /// discipline-colour legend so the produced view is never empty.
    ///
    /// It does NOT read the <c>STING_*_SYMBOLS.json</c> catalogues directly —
    /// those describe symbols to *create*; this view documents which symbols a
    /// project actually uses and to which standard, exactly like the electrical
    /// command it generalises.
    /// </summary>
    public static class DisciplineLegendEngine
    {
        private sealed class DisciplineScope
        {
            public string Name;
            public BuiltInCategory[] Categories;
            public Dictionary<BuiltInCategory, Color> Swatch;
            public string Footer;
        }

        // Discipline code → category scope + per-category swatch colour + footer.
        private static readonly Dictionary<string, DisciplineScope> Scopes =
            new Dictionary<string, DisciplineScope>(StringComparer.OrdinalIgnoreCase)
            {
                ["M"] = new DisciplineScope
                {
                    Name = "Mechanical",
                    Categories = new[]
                    {
                        BuiltInCategory.OST_MechanicalEquipment,
                        BuiltInCategory.OST_DuctTerminal,
                        BuiltInCategory.OST_DuctAccessory,
                        BuiltInCategory.OST_DuctFitting,
                    },
                    Swatch = new Dictionary<BuiltInCategory, Color>
                    {
                        { BuiltInCategory.OST_MechanicalEquipment, new Color(0, 150, 136) },   // teal
                        { BuiltInCategory.OST_DuctTerminal,        new Color(76, 175, 80) },   // green
                        { BuiltInCategory.OST_DuctAccessory,       new Color(139, 195, 74) },  // light green
                        { BuiltInCategory.OST_DuctFitting,         new Color(0, 188, 212) },   // cyan
                    },
                    Footer = "Per CIBSE Guide B / ASHRAE / BS 1553. Generated by STING Tools — " +
                             "verify symbol families match the project standard.",
                },
                ["P"] = new DisciplineScope
                {
                    Name = "Plumbing",
                    Categories = new[]
                    {
                        BuiltInCategory.OST_PlumbingFixtures,
                        BuiltInCategory.OST_PipeAccessory,
                        BuiltInCategory.OST_PipeFitting,
                        BuiltInCategory.OST_Sprinklers,
                    },
                    Swatch = new Dictionary<BuiltInCategory, Color>
                    {
                        { BuiltInCategory.OST_PlumbingFixtures, new Color(3, 169, 244) },  // light blue
                        { BuiltInCategory.OST_PipeAccessory,    new Color(0, 121, 107) },  // dark teal
                        { BuiltInCategory.OST_PipeFitting,      new Color(0, 96, 100) },   // deep cyan
                        { BuiltInCategory.OST_Sprinklers,       new Color(244, 67, 54) },  // red
                    },
                    Footer = "Per BS EN 12056 / BS 1553 / Approved Document G. Generated by STING Tools — " +
                             "verify symbol families match the project standard.",
                },
                ["S"] = new DisciplineScope
                {
                    Name = "Structural",
                    Categories = new[]
                    {
                        BuiltInCategory.OST_StructuralColumns,
                        BuiltInCategory.OST_StructuralFraming,
                        BuiltInCategory.OST_StructuralFoundation,
                        BuiltInCategory.OST_StructConnections,
                    },
                    Swatch = new Dictionary<BuiltInCategory, Color>
                    {
                        { BuiltInCategory.OST_StructuralColumns,    new Color(121, 85, 72) },  // brown
                        { BuiltInCategory.OST_StructuralFraming,    new Color(96, 125, 139) }, // blue-grey
                        { BuiltInCategory.OST_StructuralFoundation, new Color(69, 90, 100) },  // slate
                        { BuiltInCategory.OST_StructConnections,    new Color(158, 158, 158) },// grey
                    },
                    Footer = "Per BS 8666 / BS EN 10210 / BS EN 1993. Generated by STING Tools — " +
                             "verify symbol families match the project standard.",
                },
                ["A"] = new DisciplineScope
                {
                    Name = "Architectural",
                    Categories = new[]
                    {
                        BuiltInCategory.OST_Doors,
                        BuiltInCategory.OST_Windows,
                        BuiltInCategory.OST_Furniture,
                        BuiltInCategory.OST_Casework,
                        BuiltInCategory.OST_SpecialityEquipment,
                    },
                    Swatch = new Dictionary<BuiltInCategory, Color>
                    {
                        { BuiltInCategory.OST_Doors,              new Color(255, 152, 0) },  // orange
                        { BuiltInCategory.OST_Windows,           new Color(3, 169, 244) },  // light blue
                        { BuiltInCategory.OST_Furniture,         new Color(156, 39, 176) }, // purple
                        { BuiltInCategory.OST_Casework,          new Color(121, 85, 72) },  // brown
                        { BuiltInCategory.OST_SpecialityEquipment,new Color(96, 125, 139) },// blue-grey
                    },
                    Footer = "Generated by STING Tools — architectural component schedule; " +
                             "verify symbol families match the project standard.",
                },
                ["E"] = new DisciplineScope
                {
                    Name = "Electrical",
                    Categories = new[]
                    {
                        BuiltInCategory.OST_LightingFixtures,
                        BuiltInCategory.OST_LightingDevices,
                        BuiltInCategory.OST_ElectricalEquipment,
                        BuiltInCategory.OST_ElectricalFixtures,
                        BuiltInCategory.OST_FireAlarmDevices,
                        BuiltInCategory.OST_DataDevices,
                        BuiltInCategory.OST_CommunicationDevices,
                    },
                    Swatch = new Dictionary<BuiltInCategory, Color>
                    {
                        { BuiltInCategory.OST_LightingFixtures,    new Color(255, 235, 59) },
                        { BuiltInCategory.OST_LightingDevices,     new Color(255, 193, 7) },
                        { BuiltInCategory.OST_ElectricalEquipment, new Color(33, 150, 243) },
                        { BuiltInCategory.OST_ElectricalFixtures,  new Color(63, 81, 181) },
                        { BuiltInCategory.OST_FireAlarmDevices,    new Color(244, 67, 54) },
                        { BuiltInCategory.OST_DataDevices,         new Color(0, 188, 212) },
                        { BuiltInCategory.OST_CommunicationDevices,new Color(121, 85, 72) },
                    },
                    Footer = "Per IEC 60617 / BS 7671. Generated by STING Tools — " +
                             "verify symbol families match the project standard.",
                },
            };

        /// <summary>True when the discipline code maps to a symbol-legend scope
        /// with real category coverage (M / E / P / S / A).</summary>
        public static bool SupportsDiscipline(string disciplineCode)
            => !string.IsNullOrEmpty(disciplineCode) && Scopes.ContainsKey(disciplineCode.Trim());

        /// <summary>Human name for a discipline code (falls back to LegendBuilder's map).</summary>
        public static string DisciplineName(string disciplineCode)
        {
            if (!string.IsNullOrEmpty(disciplineCode)
                && Scopes.TryGetValue(disciplineCode.Trim(), out var sc))
                return sc.Name;
            if (!string.IsNullOrEmpty(disciplineCode)
                && LegendBuilder.DisciplineNames.TryGetValue(disciplineCode.Trim(), out var nm))
                return nm;
            return "General";
        }

        /// <summary>
        /// Walk a discipline's categories and build one <see cref="LegendBuilder.LegendEntry"/>
        /// per unique (category, family, type). Returns an empty list when the
        /// discipline is unknown or nothing is placed. <paramref name="uniqueCount"/>
        /// receives the row count; <paramref name="standard"/> the resolved
        /// project symbol standard for the subtitle.
        /// </summary>
        internal static List<LegendBuilder.LegendEntry> BuildEntries(
            Document doc, string disciplineCode, out int uniqueCount, out string standard)
        {
            uniqueCount = 0;
            standard = "";
            var entries = new List<LegendBuilder.LegendEntry>();
            if (doc == null) return entries;

            try { standard = SymbolStandardResolver.ResolveStandard(doc, null, null) ?? ""; }
            catch (Exception ex) { StingLog.Warn($"DisciplineLegend std: {ex.Message}"); }
            if (string.IsNullOrEmpty(standard)) standard = "Mixed (per family)";

            if (string.IsNullOrEmpty(disciplineCode)
                || !Scopes.TryGetValue(disciplineCode.Trim(), out var scope))
                return entries;

            var groups = new Dictionary<string, RowGroup>();
            foreach (var cat in scope.Categories)
            {
                try
                {
                    foreach (var fi in new FilteredElementCollector(doc)
                        .OfCategory(cat).WhereElementIsNotElementType()
                        .OfType<FamilyInstance>())
                    {
                        try
                        {
                            string famName = fi.Symbol?.FamilyName ?? "—";
                            string typeName = fi.Symbol?.Name ?? "—";
                            string key = $"{(int)cat}|{famName}|{typeName}";
                            if (!groups.TryGetValue(key, out var g))
                            {
                                string conceptId = "";
                                string symStd = "";
                                try
                                {
                                    conceptId = fi.LookupParameter("STING_SYMBOL_ID")?.AsString() ?? "";
                                    symStd = fi.LookupParameter("STING_SYMBOL_STANDARD")?.AsString() ?? "";
                                }
                                catch (Exception ex) { StingLog.Warn($"DisciplineLegend param: {ex.Message}"); }
                                if (string.IsNullOrEmpty(conceptId))
                                    try { conceptId = SymbolConceptRegistry.GetConceptForFamily(famName) ?? ""; }
                                    catch (Exception ex) { StingLog.Warn($"DisciplineLegend concept: {ex.Message}"); }
                                string description = "";
                                if (!string.IsNullOrEmpty(conceptId))
                                    try { description = SymbolConceptRegistry.GetConcept(conceptId)?.Name ?? ""; }
                                    catch (Exception ex) { StingLog.Warn($"DisciplineLegend desc: {ex.Message}"); }
                                g = new RowGroup
                                {
                                    Category = cat,
                                    FamilyName = famName,
                                    TypeName = typeName,
                                    ConceptId = conceptId,
                                    Description = description,
                                    Standard = string.IsNullOrEmpty(symStd) ? standard : symStd,
                                    Count = 0,
                                };
                                groups[key] = g;
                            }
                            g.Count++;
                        }
                        catch (Exception ex) { StingLog.Warn($"DisciplineLegend instance: {ex.Message}"); }
                    }
                }
                catch (Exception ex) { StingLog.Warn($"DisciplineLegend cat {cat}: {ex.Message}"); }
            }

            entries = groups.Values
                .OrderBy(g => Array.IndexOf(scope.Categories, g.Category))
                .ThenBy(g => g.ConceptId)
                .ThenBy(g => g.FamilyName)
                .ThenBy(g => g.TypeName)
                .Select(g => new LegendBuilder.LegendEntry
                {
                    Color = scope.Swatch.TryGetValue(g.Category, out var c) ? c : new Color(128, 128, 128),
                    Label = $"{g.FamilyName} : {g.TypeName}",
                    Description = string.IsNullOrEmpty(g.ConceptId)
                        ? $"{g.Category.ToString().Replace("OST_", "")} · {g.Count} placed"
                        : $"{g.ConceptId} — {g.Description} · {g.Standard} · {g.Count} placed",
                    Bold = false,
                    Italic = false,
                })
                .ToList();
            uniqueCount = entries.Count;
            return entries;
        }

        /// <summary>
        /// Build a discipline-colour fallback legend (one row per STING
        /// discipline) so a General / empty legend view is still populated.
        /// </summary>
        private static List<LegendBuilder.LegendEntry> BuildDisciplineColourEntries()
        {
            var palette = new Dictionary<string, Color>(StringComparer.OrdinalIgnoreCase)
            {
                { "A", new Color(255, 152, 0) },  { "S", new Color(96, 125, 139) },
                { "M", new Color(0, 150, 136) },  { "E", new Color(33, 150, 243) },
                { "P", new Color(3, 169, 244) },  { "FP", new Color(244, 67, 54) },
                { "LV", new Color(156, 39, 176) },{ "G", new Color(120, 144, 156) },
            };
            var list = new List<LegendBuilder.LegendEntry>();
            foreach (var kv in LegendBuilder.DisciplineNames)
            {
                list.Add(new LegendBuilder.LegendEntry
                {
                    Color = palette.TryGetValue(kv.Key, out var c) ? c : new Color(128, 128, 128),
                    Label = $"{kv.Key} — {kv.Value}",
                    Description = "Discipline colour band",
                    Bold = false,
                    Italic = false,
                });
            }
            return list;
        }

        /// <summary>
        /// Create (and populate) a legend view for a discipline. Must be called
        /// inside an active Transaction. Falls back to a discipline-colour
        /// legend when the discipline has no placed components, so the returned
        /// view is always populated. Returns null only on hard failure.
        /// </summary>
        public static View CreateDisciplineLegend(Document doc, string disciplineCode, out int uniqueCount)
        {
            var entries = BuildEntries(doc, disciplineCode, out uniqueCount, out var standard);
            bool fellBack = false;
            if (entries.Count == 0)
            {
                entries = BuildDisciplineColourEntries();
                fellBack = true;
            }

            string discName = DisciplineName(disciplineCode);
            string footer = (!string.IsNullOrEmpty(disciplineCode)
                             && Scopes.TryGetValue(disciplineCode.Trim(), out var sc))
                ? sc.Footer
                : "Generated by STING Tools.";

            var config = new LegendBuilder.LegendConfig
            {
                Title = $"{discName} Symbols Legend",
                Subtitle = fellBack
                    ? $"Discipline colour reference  ·  {entries.Count} disciplines  ·  {DateTime.Now:yyyy-MM-dd}"
                    : $"Project standard: {standard}  ·  {entries.Count} unique symbols  ·  {DateTime.Now:yyyy-MM-dd}",
                Columns = entries.Count > 30 ? 2 : 1,
                ColumnWidth = 0.45,
                ShowCounts = false,
                IncludeTimestamp = true,
                Footer = footer,
                DrawSwatchBorders = true,
                DrawSeparators = true,
            };
            return LegendBuilder.CreateLegendView(doc, entries, config);
        }

        private sealed class RowGroup
        {
            public BuiltInCategory Category;
            public string FamilyName, TypeName, ConceptId, Description, Standard;
            public int Count;
        }
    }
}
