// StingTools — Drawing Template Manager · Week 3
//
// DrawingTypeStamper writes two shared parameters onto any view or
// sheet a STING generator creates — so the Project Browser, the
// style-propagation IUpdater, and downstream audits can all see
// which Drawing Type produced which artefact:
//
//   STING_DRAWING_TYPE_ID_TXT   (text)  — the dt.Id
//   STING_STYLE_LOCKED_BOOL     (bool)  — "don't re-apply on edit"
//
// The two parameters are declared in MR_PARAMETERS.txt with stable
// GUIDs (see Data/MR_PARAMETERS.txt). Parameter binding happens once
// per project via LoadSharedParams / StingCompliance wiring; Stamp()
// is a no-op on projects where the binding hasn't happened yet.
//
// Worksharing: Stamp() checks that the element is editable by the
// current user before writing — avoids 'cannot modify element owned
// by another user' exceptions when running batch generators on a
// shared model.

using System;
using Autodesk.Revit.DB;

namespace StingTools.Core.Drawing
{
    public static class DrawingTypeStamper
    {
        public const string PARAM_DRAWING_TYPE_ID   = "STING_DRAWING_TYPE_ID_TXT";
        public const string PARAM_STYLE_LOCKED       = "STING_STYLE_LOCKED_BOOL";
        public const string PARAM_DRAWING_PACKAGE_ID = "STING_DRAWING_PACKAGE_ID_TXT";
        public const string PARAM_SHEET_SEQUENCE     = "STING_SHEET_SEQUENCE_INT";

        /// <summary>
        /// Stamp the DrawingType id onto the given element (view or
        /// sheet). Idempotent — writing the same value twice is a
        /// no-op. Safe to call without an active transaction (the
        /// write is wrapped by the caller's transaction).
        /// </summary>
        public static bool Stamp(Element el, string drawingTypeId)
        {
            if (el == null || string.IsNullOrWhiteSpace(drawingTypeId)) return false;
            if (!IsEditable(el)) return false;

            try
            {
                var p = el.LookupParameter(PARAM_DRAWING_TYPE_ID);
                if (p == null || p.IsReadOnly || p.StorageType != StorageType.String) return false;
                var current = p.AsString();
                if (string.Equals(current, drawingTypeId, StringComparison.Ordinal)) return true;
                p.Set(drawingTypeId);
                return true;
            }
            catch (Exception ex)
            {
                StingTools.Core.StingLog.Warn(
                    $"DrawingTypeStamper.Stamp({el.Id}, '{drawingTypeId}'): {ex.Message}");
                return false;
            }
        }

        public static string Read(Element el)
        {
            if (el == null) return null;
            try
            {
                var p = el.LookupParameter(PARAM_DRAWING_TYPE_ID);
                return p?.StorageType == StorageType.String ? p.AsString() : null;
            }
            catch { return null; }
        }

        public static bool IsLocked(Element el)
        {
            if (el == null) return false;
            try
            {
                var p = el.LookupParameter(PARAM_STYLE_LOCKED);
                return p != null
                    && p.StorageType == StorageType.Integer
                    && p.AsInteger() != 0;
            }
            catch { return false; }
        }

        public static void SetLocked(Element el, bool locked)
        {
            if (el == null || !IsEditable(el)) return;
            try
            {
                var p = el.LookupParameter(PARAM_STYLE_LOCKED);
                if (p == null || p.IsReadOnly || p.StorageType != StorageType.Integer) return;
                p.Set(locked ? 1 : 0);
            }
            catch (Exception ex)
            {
                StingTools.Core.StingLog.Warn(
                    $"DrawingTypeStamper.SetLocked({el.Id}, {locked}): {ex.Message}");
            }
        }

        /// <summary>
        /// Read the raw stamp string from a view without any null-coalescing.
        /// Used by ManagedTemplateSyncer to determine whether a template
        /// was generated by a specific pack.
        /// </summary>
        public static string ReadRaw(View v)
        {
            if (v == null) return null;
            try
            {
                var p = v.LookupParameter(PARAM_DRAWING_TYPE_ID);
                if (p == null) return null;
                return p.StorageType == StorageType.String ? p.AsString() : null;
            }
            catch { return null; }
        }

        /// <summary>
        /// Stamp a drawing-package id onto a view or sheet.
        /// Idempotent — writing the same value twice is a no-op.
        /// </summary>
        public static bool StampPackage(Element el, string packageId)
        {
            if (el == null || string.IsNullOrWhiteSpace(packageId)) return false;
            if (!IsEditable(el)) return false;
            try
            {
                var p = el.LookupParameter(PARAM_DRAWING_PACKAGE_ID);
                if (p == null || p.IsReadOnly || p.StorageType != StorageType.String) return false;
                if (string.Equals(p.AsString(), packageId, StringComparison.Ordinal)) return true;
                p.Set(packageId);
                return true;
            }
            catch (Exception ex)
            {
                StingTools.Core.StingLog.Warn(
                    $"DrawingTypeStamper.StampPackage({el.Id}, '{packageId}'): {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Stamp the 1-based sheet sequence number onto a ViewSheet.
        /// </summary>
        public static bool StampSheetSequence(ViewSheet sheet, int sequence)
        {
            if (sheet == null || sequence <= 0) return false;
            if (!IsEditable(sheet)) return false;
            try
            {
                var p = sheet.LookupParameter(PARAM_SHEET_SEQUENCE);
                if (p == null || p.IsReadOnly || p.StorageType != StorageType.Integer) return false;
                if (p.AsInteger() == sequence) return true;
                p.Set(sequence);
                return true;
            }
            catch (Exception ex)
            {
                StingTools.Core.StingLog.Warn(
                    $"DrawingTypeStamper.StampSheetSequence({sheet.Id}, {sequence}): {ex.Message}");
                return false;
            }
        }

        /// <summary>
        /// Worksharing guard — true if the current user owns the
        /// element's checkout or if the model is not workshared.
        /// Avoids 'cannot modify' exceptions on federated runs.
        /// </summary>
        private static bool IsEditable(Element el)
        {
            try
            {
                var doc = el.Document;
                if (doc == null) return false;
                if (!doc.IsWorkshared) return true;
                var status = WorksharingUtils.GetCheckoutStatus(doc, el.Id);
                return status == CheckoutStatus.OwnedByCurrentUser
                    || status == CheckoutStatus.NotOwned;
            }
            catch { return true; }
        }
    }
}
