// StingTools — Drawing Template Manager · DRAW-2
//
// Seven drawing types declare AutoAnnotateFlowArrow, and MepAnnotator places
// a generic-annotation family to do it — a family that shipped nowhere. With
// none loaded the rule reported "no flow-arrow annotation family found" and
// placed nothing, on every run, forever: correct behaviour with no way out.
//
// This command authors that family from Revit's own Generic Annotation
// template, saves it to the project content folder that ContentRoots already
// searches, and loads it. MepAnnotator resolves it by name, and falls back to
// loading it from disk when a project has the file but not the family.
//
// NOT VERIFIED IN REVIT. Family-editor geometry (detail curves, filled
// region) is exactly the kind of API surface that only proves itself when it
// runs. Check: arrow visible, head at +X, scales with the view.

using System;
using System.IO;
using System.Linq;
using Autodesk.Revit.Attributes;
using Autodesk.Revit.DB;
using Autodesk.Revit.UI;
using StingTools.Core;

namespace StingTools.Commands.Drawing
{
    [Transaction(TransactionMode.Manual)]
    [Regeneration(RegenerationOption.Manual)]
    public class BuildFlowArrowFamilyCommand : IExternalCommand
    {
        /// <summary>The family name MepAnnotator looks for first.</summary>
        public const string FamilyName = StingTools.Core.Drawing.Dimensioning.MepAnnotator.FlowArrowFamily;

        public Result Execute(ExternalCommandData data, ref string msg, ElementSet els)
        {
            var uiapp = data?.Application ?? StingTools.UI.StingCommandHandler.CurrentApp;
            var doc = uiapp?.ActiveUIDocument?.Document;
            if (doc == null) { msg = "No document open."; return Result.Failed; }
            if (doc.IsFamilyDocument) { msg = "Run this from a project, not a family."; return Result.Failed; }

            string savePath;
            try
            {
                savePath = Author(uiapp.Application, doc);
            }
            catch (Exception ex)
            {
                StingLog.Error("BuildFlowArrowFamily", ex);
                TaskDialog.Show("STING — Flow Arrow", $"Could not author {FamilyName}: {ex.Message}");
                return Result.Failed;
            }

            bool loaded;
            using (var tx = new Transaction(doc, "STING — Load flow-arrow family"))
            {
                tx.Start();
                loaded = doc.LoadFamily(savePath, new OverwriteLoadOptions(), out _);
                tx.Commit();
            }
            TaskDialog.Show("STING — Flow Arrow",
                (loaded ? $"{FamilyName} authored and loaded." : $"{FamilyName} authored; it was already loaded and was updated.") +
                $"\n\nSaved to:\n{savePath}\n\nDrawing types that declare AutoAnnotateFlowArrow will now place it. " +
                "This family was generated by code — check its appearance once before issuing drawings.");
            return Result.Succeeded;
        }

        /// <summary>Author the family and return where it was saved.</summary>
        internal static string Author(Autodesk.Revit.ApplicationServices.Application app, Document projectDoc)
        {
            var template = FindGenericAnnotationTemplate(app)
                ?? throw new FileNotFoundException(
                    "Revit's 'Generic Annotation.rft' template was not found under the family template path " +
                    $"'{app.FamilyTemplatePath}'. Install the Revit content, or set the template path in Revit Options.");

            var dir = StingPaths.Meta(projectDoc, "_BIM_COORD", "Families");
            Directory.CreateDirectory(dir);
            var path = Path.Combine(dir, FamilyName + ".rfa");

            var fam = app.NewFamilyDocument(template)
                ?? throw new InvalidOperationException("NewFamilyDocument returned null.");
            try
            {
                using (var tx = new Transaction(fam, "Draw flow arrow"))
                {
                    tx.Start();
                    // The template ships a placeholder text note; an arrow with the
                    // word "Note" beside it is not an arrow.
                    var notes = new FilteredElementCollector(fam).OfClass(typeof(TextNote)).ToElementIds();
                    if (notes.Count > 0) fam.Delete(notes);

                    var view = new FilteredElementCollector(fam).OfClass(typeof(View)).Cast<View>()
                        .First(v => !v.IsTemplate);

                    // Paper millimetres. Shaft 6mm, head 2.5mm long x 2mm wide, pointing +X —
                    // MepAnnotator rotates the instance to the flow direction.
                    double mm = 1.0 / 304.8;
                    var tail = new XYZ(-3 * mm, 0, 0);
                    var neck = new XYZ(0.5 * mm, 0, 0);
                    var tip  = new XYZ(3 * mm, 0, 0);
                    var up   = new XYZ(0.5 * mm, 1 * mm, 0);
                    var dn   = new XYZ(0.5 * mm, -1 * mm, 0);

                    fam.FamilyCreate.NewDetailCurve(view, Line.CreateBound(tail, neck));
                    var headLoop = CurveLoop.Create(new Curve[]
                    {
                        Line.CreateBound(up, tip), Line.CreateBound(tip, dn), Line.CreateBound(dn, up),
                    });

                    var fillType = new FilteredElementCollector(fam).OfClass(typeof(FilledRegionType))
                        .Cast<FilledRegionType>().FirstOrDefault();
                    if (fillType != null)
                        FilledRegion.Create(fam, fillType.Id, view.Id, new[] { headLoop });
                    else
                        foreach (var c in headLoop) fam.FamilyCreate.NewDetailCurve(view, c);

                    tx.Commit();
                }
                fam.SaveAs(path, new SaveAsOptions { OverwriteExistingFile = true });
            }
            finally
            {
                fam.Close(false);
            }
            return path;
        }

        private static string FindGenericAnnotationTemplate(Autodesk.Revit.ApplicationServices.Application app)
        {
            var root = app.FamilyTemplatePath;
            if (string.IsNullOrEmpty(root) || !Directory.Exists(root)) return null;
            try
            {
                return Directory.GetFiles(root, "*Generic Annotation.rft", SearchOption.AllDirectories)
                    .OrderBy(p => p.IndexOf("Metric", StringComparison.OrdinalIgnoreCase) >= 0 ? 0 : 1)
                    .ThenBy(p => p.Length)
                    .FirstOrDefault();
            }
            catch (Exception ex)
            {
                StingLog.Warn($"FindGenericAnnotationTemplate: {ex.Message}");
                return null;
            }
        }

        private sealed class OverwriteLoadOptions : IFamilyLoadOptions
        {
            public bool OnFamilyFound(bool familyInUse, out bool overwriteParameterValues)
            { overwriteParameterValues = false; return true; }
            public bool OnSharedFamilyFound(Family sharedFamily, bool familyInUse, out FamilySource source, out bool overwriteParameterValues)
            { source = FamilySource.Family; overwriteParameterValues = false; return true; }
        }
    }
}
