using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

namespace StingTools.Tools.DumpBip
{
    /// <summary>
    /// Dumps Autodesk.Revit.DB.BuiltInParameter member names from RevitAPI.dll
    /// metadata. See the .csproj header for why and how it is run.
    /// </summary>
    internal static class Program
    {
        private static int Main(string[] args)
        {
            string dll = args.Length > 0 ? args[0] : @"C:\Program Files\Autodesk\Revit 2025\RevitAPI.dll";
            if (!File.Exists(dll)) { Console.Error.WriteLine("RevitAPI.dll not found: " + dll); return 2; }

            string repo = FindRepoRoot();
            string outPath = Path.Combine(repo, "StingTools.Tags.Tests", "Fixtures", "BuiltInParameterNames.txt");

            var names = new List<string>();
            using (var fs = File.OpenRead(dll))
            using (var pe = new PEReader(fs))
            {
                var md = pe.GetMetadataReader();
                foreach (var th in md.TypeDefinitions)
                {
                    var td = md.GetTypeDefinition(th);
                    if (md.GetString(td.Name) != "BuiltInParameter" || md.GetString(td.Namespace) != "Autodesk.Revit.DB")
                        continue;
                    foreach (var fh in td.GetFields())
                    {
                        var f = md.GetFieldDefinition(fh);
                        // Enum members are the static literal fields; skip value__.
                        if ((f.Attributes & System.Reflection.FieldAttributes.Literal) == 0) continue;
                        names.Add(md.GetString(f.Name));
                    }
                }
            }
            if (names.Count == 0) { Console.Error.WriteLine("BuiltInParameter not found in " + dll); return 3; }

            names = names.Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal).ToList();
            var header = new[]
            {
                "# Autodesk.Revit.DB.BuiltInParameter member names, one per line.",
                "# Generated by tools/DumpBuiltInParameterNames from: " + Path.GetFileName(Path.GetDirectoryName(dll)) + "/RevitAPI.dll",
                "# Do not hand-edit; regenerate. Read by AecFilterParameterResolutionTests.",
            };
            File.WriteAllText(outPath, string.Join("\n", header.Concat(names)) + "\n");
            Console.WriteLine($"Wrote {names.Count} names to {outPath}");
            return 0;
        }

        private static string FindRepoRoot()
        {
            var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, "StingTools.Tags.Tests")))
                dir = dir.Parent;
            if (dir == null) throw new InvalidOperationException("Run from inside the repository.");
            return dir.FullName;
        }
    }
}
