"""Generate the label migration sheet: ten tier BOOLs -> one depth INTEGER.

Reads the authoritative build sheet and emits, per row, the exact formula to
paste. Generated rather than hand-written because 70 near-identical formulas
are precisely where a human transcription slips, and a slipped tier number is
invisible: the row simply draws at the wrong depth.

Revit has no >= operator (measured 2026-09-23: "Operator not expected: ="), so
tier N becomes `> N-1`, which is the same set over integers.

Usage:  python tools/gen_integer_gate_migration.py [--check]
        --check exits 1 if the generated sheet differs from the one on disk.
"""
import io, os, re, sys

SRC = "docs/UNIVERSAL_TAG_LABEL_BUILD_SHEET.md"
OUT = "docs/UNIVERSAL_TAG_LABEL_INTEGER_MIGRATION.md"

GATE = re.compile(r"TAG_PARA_STATE_(\d+)_BOOL")
NUMBERED = re.compile(r"^\|\s*(\d+)\s*\|")
FORMULA = re.compile(r"`([^`]*)`")


def rows():
    """Every numbered row, formula or not.

    Parsed by splitting cells rather than by one regex over the whole line.
    The regex version required the formula cell to END at the closing
    backtick, so rows 22 and 50 - which carry a trailing `<br>_(note)_` -
    were dropped silently, along with row 1, which has no formula at all.
    Three rows vanished from a sheet that claimed to list every one, and two
    of them needed migrating. A parser that skips what it does not recognise
    reports a clean run over a partial file.
    """
    out = []
    for line in io.open(SRC, encoding="utf-8").read().split("\n"):
        s = line.strip()
        if not NUMBERED.match(s):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) < 4:
            continue
        cell = cells[3]
        fm = FORMULA.search(cell)
        formula = fm.group(1).strip() if fm else ""
        note = cell[fm.end():].strip() if fm else ""
        out.append((int(cells[0]), cells[1], cells[2], formula, note))
    return out


def convert(formula):
    """Rewrite the gate; leave everything else byte-identical."""
    return GATE.sub(lambda m: "TAG_DEPTH_TIER_INT > %d" % (int(m.group(1)) - 1), formula)


def build():
    all_rows = rows()

    # INSTRUMENT CHECK. Count the numbered rows independently and insist the
    # parse kept every one. Without this the generator reports success over
    # whatever it happened to understand - which is how rows 1, 22 and 50 went
    # missing from the first version of this sheet.
    raw = io.open(SRC, encoding="utf-8").read().split("\n")
    nums = [int(NUMBERED.match(l.strip()).group(1))
            for l in raw if NUMBERED.match(l.strip())]
    if len(all_rows) != len(nums):
        dropped = sorted(set(nums) - set(r[0] for r in all_rows))
        sys.stderr.write("FAILED: %s has %d numbered rows, %d parsed. Dropped: %s\n"
                         % (SRC, len(nums), len(all_rows), dropped))
        sys.exit(2)
    if len(nums) < 50:
        sys.stderr.write("FAILED: only %d rows found in %s; the table shape changed.\n"
                         % (len(nums), SRC))
        sys.exit(2)

    changed = [r for r in all_rows if GATE.search(r[3])]
    if not changed:
        sys.stderr.write("FAILED: no row references a tier gate; nothing to migrate.\n")
        sys.exit(2)

    L = []
    L.append("<!-- GENERATED by tools/gen_integer_gate_migration.py - do not hand-edit.")
    L.append("     Regenerate after any change to UNIVERSAL_TAG_LABEL_BUILD_SHEET.md. -->")
    L.append("")
    L.append("# Universal tag label - ten tier BOOLs to one depth INTEGER")
    L.append("")
    L.append("**%d of %d rows change.** Every one is the same edit: the gate becomes a "
             "comparison against `TAG_DEPTH_TIER_INT`. Nothing else in the row moves - "
             "not the name, the prefix, the suffix, Spaces or Break."
             % (len(changed), len(all_rows)))
    L.append("")
    L.append("## Why")
    L.append("")
    L.append("Measured in Revit on 2026-09-23, on a live air terminal:")
    L.append("")
    L.append("- A tier gate is read from the **tagged element's type**, not from the tag "
             "type. Ticking `TAG_PARA_STATE_6_BOOL` on the air terminal type made the T6 "
             "rows draw; unticking it removed them. The copies `Set depth` writes on the "
             "tag type are inert for rendering.")
    L.append("- An **integer comparison works the same way**: "
             "`if(TAG_DEPTH_TIER_INT > 5, ASS_TAG_7F_TXT, \"\")` with the value 6 drew "
             "its row.")
    L.append("")
    L.append("So the gate must be bound to the element either way. Ten booleans and one "
             "integer are both feasible; the integer is one binding instead of ten, makes "
             "a state like \"all ten on at depth 2\" unrepresentable, and makes tier 11 "
             "free - no new shared parameter, no new binding, no new spec row.")
    L.append("")
    L.append("## Two Revit rules that bite")
    L.append("")
    L.append("1. **There is no `>=`.** Revit answers `Operator not expected: =`. Tier N is "
             "written `> N-1`, the same set over integers. Every formula below already "
             "accounts for it - do not \"correct\" them back.")
    L.append("2. **An unset integer reads as 0**, so every gated row stays hidden until "
             "`TAG_DEPTH_TIER_INT` has a value. That is the correct default, not a bug.")
    L.append("")
    L.append("## Before you start")
    L.append("")
    L.append("Bind `TAG_DEPTH_TIER_INT` to the tagged categories, **Type**-scoped. Without "
             "it the identifier does not resolve and every row below returns empty.")
    L.append("")
    L.append("## The rows to change")
    L.append("")
    L.append("| # | Tier | Row name | Replace the formula with |")
    L.append("|---|---|---|---|")
    for num, tier, name, formula, note in changed:
        L.append("| %d | %s | %s | `%s` |%s"
                 % (num, tier, name, convert(formula), (" " + note) if note else ""))
    L.append("")

    unchanged = [r for r in all_rows if not GATE.search(r[3])]
    L.append("## Rows that do NOT change (%d)" % len(unchanged))
    L.append("")
    L.append("They carry no tier gate. Leave them exactly as they are.")
    L.append("")
    L.append("| # | Tier | Row name |")
    L.append("|---|---|---|")
    for num, tier, name, _f, _n in unchanged:
        L.append("| %d | %s | %s |"
                 % (num, tier, name if name not in ("---", "") else "(plain parameter, no formula)"))
    L.append("")
    L.append("## After")
    L.append("")
    L.append("1. Load the master into a project and confirm one gated row draws at a depth "
             "that should show it, and does **not** at a depth that should not. Check both "
             "- a row that always draws is as wrong as one that never does.")
    L.append("2. Run `Propagate_UniversalTag` to clone the master across the library.")
    L.append("3. `Set depth` writes `TAG_DEPTH_TIER_INT` on element types, capped per "
             "category by `STING_TOKEN_DEPTH_OVERRIDES.json`.")
    L.append("")
    return "\n".join(L) + "\n"


text = build()
if "--check" in sys.argv:
    cur = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    if cur != text:
        sys.stderr.write("STALE: %s differs from the generator. Re-run:\n"
                         "    python tools/gen_integer_gate_migration.py\n" % OUT)
        sys.exit(1)
    print("%s is current." % OUT)
else:
    io.open(OUT, "w", encoding="utf-8", newline="").write(text)
    print("wrote %s" % OUT)
