"""Builds a Revit shared-parameter file holding ONLY what the LPS master needs.

The GUIDs are copied from MR_PARAMETERS.txt unchanged. That is the whole point:
a shared parameter IS its GUID, so a regenerated GUID would create a different
parameter that happens to share a name - it would bind, it would look right, and
it would never receive a value from anything STING writes.
"""
import io
import re

SHEET = "docs/LPS_TAG_MASTER_BUILD_SHEET.md"
MASTER = "StingTools/Data/MR_PARAMETERS.txt"
OUT = "StingTools/Data/MR_PARAMETERS_LPS_MASTER.txt"

# ── what the master needs, read from the sheet itself ───────────────────────
wanted, order = set(), []


def want(p):
    if p and p not in wanted:
        wanted.add(p)
        order.append(p)


for line in io.open(SHEET, encoding="utf-8"):
    m = re.match(r"^\|\s*\d+\s*\|\s*(T\d+)\s*\|([^|]*)\|([^|]*)\|", line)
    if m:
        tier, name, formula = m.group(1), m.group(2).strip(), m.group(3)
        # T1 rows name the parameter directly; the rest carry it in the formula.
        f = re.search(r"TAG_PARA_STATE_\d+_BOOL,\s*([A-Z0-9_]+)", formula)
        if f:
            want(f.group(1))
            want("TAG_PARA_STATE_%s_BOOL" % tier[1:])   # the tier gate itself
        else:
            n = re.search(r"`([A-Z0-9_]+)`", name)
            if n:
                want(n.group(1))
        continue
    # Warning rows: | SEVERITY | `PARAM` | condition |
    w = re.match(r"^\|\s*(HIGH|MEDIUM|CRITICAL|MED|LOW)\s*\|\s*`([A-Z0-9_]+)`", line)
    if w:
        want(w.group(2))

# The paragraph container the nine declare, which no row names.
want("ELC_TAG_7_PARA_LPS_TXT")

# ── pull the real definitions ───────────────────────────────────────────────
groups, params, missing = {}, {}, []
for line in io.open(MASTER, encoding="utf-8-sig"):
    f = line.rstrip("\n").split("\t")
    if f[0] == "GROUP" and len(f) >= 3:
        groups[f[1]] = f[2]
    elif f[0] == "PARAM" and len(f) >= 3 and f[2] in wanted:
        params.setdefault(f[2], line.rstrip("\n"))

missing = [p for p in order if p not in params]

# Only the groups the kept parameters actually reference.
used_groups = sorted({p.split("\t")[5] for p in params.values() if len(p.split("\t")) > 5},
                     key=lambda g: int(g) if g.isdigit() else 0)

out = []
out.append("# This is a Revit shared parameter file.")
out.append("# Do not edit manually.")
out.append("#")
out.append("# STING - LPS TAG MASTER subset, generated by tools/gen_lps_params.py.")
out.append("# %d parameters, for hand-authoring STING_LPS_Tag_Universal." % len(params))
out.append("# See docs/LPS_TAG_MASTER_BUILD_SHEET.md.")
out.append("#")
out.append("# GUIDs are copied from MR_PARAMETERS.txt UNCHANGED. A shared parameter IS")
out.append("# its GUID: a fresh one would create a different parameter with the same")
out.append("# name - it would bind, it would look correct, and it would never receive a")
out.append("# value from anything STING writes.")
out.append("#")
out.append("# Point Revit at this file ONLY while authoring the master, then set it back")
out.append("# to MR_PARAMETERS.txt. It is a subset, not a replacement.")
out.append("*META\tVERSION\tMINVERSION")
out.append("META\t2\t1")
out.append("*GROUP\tID\tNAME")
for g in used_groups:
    out.append("GROUP\t%s\t%s" % (g, groups.get(g, "STING")))
out.append("*PARAM\tGUID\tNAME\tDATATYPE\tDATACATEGORY\tGROUP\tVISIBLE\tDESCRIPTION\tUSERMODIFIABLE\tHIDEWHENNOVALUE")
for p in order:
    if p in params:
        out.append(params[p])

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")

print("wrote %s" % OUT)
print("  wanted   : %d" % len(order))
print("  found    : %d" % len(params))
print("  groups   : %d" % len(used_groups))
if missing:
    print("  MISSING  : %d — these are named by the build sheet but are NOT in" % len(missing))
    print("             MR_PARAMETERS.txt, so the label rows would have nothing to bind to:")
    for m in missing:
        print("               " + m)
