#!/usr/bin/env python3
"""Regenerate the two human-readable binding views from the binding spec.

WHY THIS EXISTS

Load Shared Parameters and Reconcile Bindings bind from RESOLVED_BINDINGS.csv,
which tools/param_binding_resolver.py generates. Two older files describe the same
thing and were edited by hand, so they drifted: on 2026-09-28, 588 parameters
named different categories in PARAMETER_CATEGORIES.csv than in CATEGORY_BINDINGS.csv,
and the two views covered about 1,300 and 1,600 of 3,666 parameters. CATEGORY_BINDINGS.csv
is the resolver's hand-authored input (only its Yes rows are honoured), not a
description of what binds, so it was the wrong thing to compare them with.

This script derives both views from RESOLVED_BINDINGS.csv and MR_PARAMETERS.txt, so
they say exactly what binds and cannot drift. Do not edit the outputs by hand.

    PARAMETER_CATEGORIES.csv   one row per bound parameter: display name, data type,
                               binding (always Instance: the loader binds instance),
                               categories, group, GUID, description. "<ALL>" means the
                               universal set in PARAMETER_REGISTRY.json.
    BINDING_COVERAGE_MATRIX.csv  parameter x category 0/1 grid; <ALL> expands to the
                               universal categories among the columns.

Display names already in PARAMETER_CATEGORIES.csv are kept; a new parameter gets
one derived from its name.

    python tools/gen_binding_views.py           # write
    python tools/gen_binding_views.py --check   # exit 1 if either file is stale
"""
import csv
import io
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "StingTools" / "Data"
TXT = DATA / "MR_PARAMETERS.txt"
SPEC = DATA / "RESOLVED_BINDINGS.csv"
REGISTRY = DATA / "PARAMETER_REGISTRY.json"
PC = DATA / "PARAMETER_CATEGORIES.csv"
MATRIX = DATA / "BINDING_COVERAGE_MATRIX.csv"
ALL = "<ALL>"

HEADER_NOTE = ("# Generated by tools/gen_binding_views.py from RESOLVED_BINDINGS.csv and "
               "MR_PARAMETERS.txt -- do not edit by hand. {what}\n")

SUFFIXES = ("_TXT", "_NR", "_BOOL", "_INT", "_NUM")


def read_params():
    groups, params = {}, {}
    for line in TXT.read_text(encoding="utf-8-sig").splitlines():
        c = line.split("\t")
        if c[0] == "GROUP" and len(c) > 2:
            groups[c[1]] = c[2]
        elif c[0] == "PARAM" and len(c) > 7:
            params.setdefault(c[2], {"guid": c[1], "type": c[3], "group": c[5], "desc": c[7]})
    for p in params.values():
        p["group"] = groups.get(p["group"], p["group"])
    return params


def read_spec():
    spec = {}
    with SPEC.open(newline="", encoding="utf-8") as f:
        for row in csv.reader(f):
            if len(row) >= 2 and row[0] and not row[0].startswith("#") and row[1].strip():
                toks = [t for t in row[1].split("|") if t]
                spec[row[0]] = (ALL in toks, [t for t in toks if t != ALL])
    return spec


def existing_display_names():
    names = {}
    if not PC.exists():
        return names
    lines = [l for l in PC.read_text(encoding="utf-8-sig").splitlines() if l and not l.startswith("#")]
    for row in csv.reader(lines[1:]):
        if len(row) >= 2 and row[1].strip():
            names[row[0]] = row[1].strip()
    return names


def derive_display(name):
    stem = name
    for s in SUFFIXES:
        if stem.endswith(s):
            stem = stem[: -len(s)]
            break
    words = [w for w in stem.split("_")[1:] if w] or [stem]
    return " ".join(w.capitalize() for w in words)


def render_pc(params, spec, universal_n):
    keep = existing_display_names()
    out = io.StringIO()
    out.write(HEADER_NOTE.format(what="<ALL> = the %d universal categories in PARAMETER_REGISTRY.json." % universal_n))
    w = csv.writer(out, lineterminator="\n")
    w.writerow(["Parameter Name", "Schedule Display Name", "Data Type", "Type/Instance",
                "Categories", "Group", "GUID", "Description"])
    for name in sorted(spec):
        if name not in params:
            continue
        uni, cats = spec[name]
        p = params[name]
        cells = ([ALL] if uni else []) + cats
        w.writerow([name, keep.get(name) or derive_display(name), p["type"], "Instance",
                    ", ".join(cells), p["group"], p["guid"], p["desc"]])
    return out.getvalue()


def render_matrix(params, spec, universal):
    columns = sorted({c for uni, cats in spec.values() for c in cats} | set(universal))
    uset = set(universal)
    out = io.StringIO()
    out.write(HEADER_NOTE.format(what="<ALL> rows are 1 on every universal category."))
    w = csv.writer(out, lineterminator="\n")
    w.writerow(["Parameter_Name"] + columns)
    for name in sorted(spec):
        if name not in params:
            continue
        uni, cats = spec[name]
        on = (uset if uni else set()) | set(cats)
        w.writerow([name] + ["1" if c in on else "0" for c in columns])
    return out.getvalue()


def main():
    check = "--check" in sys.argv
    params, spec = read_params(), read_spec()
    universal = json.loads(REGISTRY.read_text(encoding="utf-8-sig"))["universal_categories"]
    outputs = {PC: render_pc(params, spec, len(universal)), MATRIX: render_matrix(params, spec, universal)}
    stale = [p.name for p, text in outputs.items()
             if not p.exists() or p.read_text(encoding="utf-8-sig") != text]
    if check:
        if stale:
            print("STALE (run python tools/gen_binding_views.py): " + ", ".join(stale))
            return 1
        print("binding views match RESOLVED_BINDINGS.csv (%d parameters)" % len(spec))
        return 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="")
    print("wrote %s (%d parameters, %d unknown to MR_PARAMETERS.txt skipped)"
          % (", ".join(p.name for p in outputs), sum(1 for n in spec if n in params),
             sum(1 for n in spec if n not in params)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
