#!/usr/bin/env python3
"""
Regenerate the gap register's headline count FROM the table rows.

WHY THIS EXISTS
---------------
The header count was hand-maintained and drifted three times in four passes —
"46 of 89", "48 of 90", "58 of 104" — each written by someone who had just closed
an item and incremented by hand. Twice it counted rows from a different table
entirely (the "Claim / What the data said" retrospective, whose first column also
looks like an ID).

That is the same drift defect this whole workstream exists to fix, sitting in the
register that was meant to track it. A number nobody can trust is worse than no
number, so this generates it.

  python3 tools/register_count.py            # report, write nothing
  python3 tools/register_count.py --apply    # rewrite the header line
  python3 tools/register_count.py --check    # exit 1 if the header is stale (CI)

WHAT COUNTS AS A GAP ROW
------------------------
A table row whose 1st cell is an ID, 2nd is a priority (P0/P1/P2/— /blank) and
3rd is a status. Anchoring on that SHAPE is what keeps the retrospective table out
of the count — its second column is prose, not a priority.
"""

import os
import re
import sys
import collections

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTER = os.path.join(REPO, "GUIDES", "STINGTOOLS_GAPS_KIBALE_REVIEW.md")

# Cells may be wrapped in ** ** anywhere — the register bolds P0 rows and bolds
# statuses like **closed**. The first version of this regex required a BARE
# priority cell, so every `| **P0** |` row failed to match and was silently
# excluded from the count. That is the same drift defect this tool exists to
# prevent, in the tool: a number computed from a subset nobody knew was a subset.
#
# Strip emphasis per cell rather than trying to spell it into one pattern.
ROW = re.compile(
    r'^\|([^|]+)\|([^|]*)\|([^|]*)\|'   # id+title | priority | status
)
ID_IN_CELL = re.compile(r'^\s*\*{0,2}\s*([A-Z]+-\d+[a-z]?)\b')


def _clean(cell):
    return cell.replace("**", "").replace("`", "").strip()

STATUS_ORDER = ["closed", "partial", "held", "blocked", "rule", "recommend", "correction", "open"]


def classify(raw):
    s = raw.lower()
    for k in ("closed", "partial", "held", "blocked"):
        if k in s:
            return k
    if "rule" in s:
        return "rule"
    if "recommend" in s or "correction" in s:
        return "recommend"
    return "open"


def scan():
    """Return {id: status} plus every id appearing on more than one row.

    A gap row is `| <ID> title | <priority> | <status> | …`. The priority cell is
    what distinguishes it from the retrospective "Claim / What the data said"
    table, whose second column is prose.
    """
    rows = {}
    dupes = collections.defaultdict(list)
    with open(REGISTER, encoding="utf-8") as fh:
        for n, line in enumerate(fh, 1):
            m = ROW.match(line)
            if not m:
                continue
            idm = ID_IN_CELL.match(m.group(1))
            if not idm:
                continue
            pri = _clean(m.group(2))
            # Priority cell must be a priority (or an explicit blank/dash), else
            # this is a different table that happens to start with an ID-shaped word.
            if pri not in ("P0", "P1", "P2", "—", "-", ""):
                continue
            gid = idm.group(1)
            st = classify(_clean(m.group(3)))
            dupes[gid].append((n, st))
            # LAST-WINS would silently prefer a stale duplicate, so record the
            # first and let the duplicate report force a human to resolve it.
            if gid not in rows:
                rows[gid] = st
    return rows, {k: v for k, v in dupes.items() if len(v) > 1}


def header_line(rows):
    c = collections.Counter(rows.values())
    total = len(rows)
    closed = c["closed"]
    bits = []
    for k in STATUS_ORDER:
        if k == "closed" or not c[k]:
            continue
        bits.append(f"{c[k]} {k}")
    tail = ", ".join(bits)
    return (f"> **{closed} of {total} entries are closed** on `claude/kibale-integration`"
            + (f" — {tail}." if tail else ".")
            + " Generated by `tools/register_count.py` from the table rows — do not hand-edit,"
              " it has drifted three times when maintained by hand.")


def main():
    rows, dupes = scan()
    line = header_line(rows)

    print(f"gap rows          : {len(rows)}")
    for k, v in collections.Counter(rows.values()).most_common():
        print(f"  {k:<10} {v}")
    if dupes:
        print(f"\nDUPLICATE ID ROWS : {len(dupes)}  (an ID must appear once)")
        for gid, occ in sorted(dupes.items()):
            print(f"  {gid}: " + ", ".join(f"line {n} ({s})" for n, s in occ))

    src = open(REGISTER, encoding="utf-8").read()
    cur = next((l for l in src.split("\n") if l.startswith("> **") and "entries are closed" in l), None)

    if "--apply" in sys.argv:
        if cur is None:
            print("\nNo header line found to replace.")
            return 1
        open(REGISTER, "w", encoding="utf-8", newline="\n").write(src.replace(cur, line, 1))
        print(f"\nwrote: {line[:90]}…")
        return 0

    if "--check" in sys.argv:
        if dupes:
            print("\nFAIL: duplicate ID rows.")
            return 1
        if cur != line:
            print("\nFAIL: header count is stale.")
            print(f"  on disk  : {cur}")
            print(f"  generated: {line}")
            return 1
        print("\nOK: header count matches the table.")
        return 0

    print(f"\ngenerated header:\n{line}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
