// StingTools v4 MVP — Phase I.5 branding token bag + export stampers.
//
// TokenBag builds the full {{placeholder}} dictionary every exporter
// substitutes into headers / footers / cover pages. StampCsvHeader
// and StampXmlComment give CSV/XML exporters one-line access to
// two-row corporate metadata so their output carries the same
// masthead as .docx / .xlsx deliverables.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Autodesk.Revit.DB;

namespace StingTools.Core.Branding
{
    public static class BrandTokens
    {
        /// <summary>
        /// Return a dictionary of {{token}} → value pairs suitable for
        /// MiniWord, ClosedXML or any string-substitution renderer.
        /// Pulls from the corporate brand manifest + Revit
        /// ProjectInformation. Caller can augment with per-document
        /// tokens after.
        /// </summary>
        public static Dictionary<string, string> For(Document doc)
        {
            var brand = CorporateBrand.For(doc);
            var proj  = doc?.ProjectInformation;
            var now   = DateTime.Now;
            var bag = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["company_name"]    = brand.CompanyName,
                ["company_short"]   = brand.CompanyShort,
                ["company_address"] = brand.CompanyAddress,
                ["company_email"]   = brand.CompanyEmail,
                ["company_website"] = brand.CompanyWebsite,
                ["company_phone"]   = brand.CompanyPhone,
                ["company_tagline"] = brand.CompanyTagline,
                ["logo_primary"]    = brand.LogoPrimary,
                ["logo_mono"]       = brand.LogoMono,

                ["palette.primary_hex"]   = brand.Palette.PrimaryHex,
                ["palette.secondary_hex"] = brand.Palette.SecondaryHex,
                ["palette.accent_hex"]    = brand.Palette.AccentHex,
                ["palette.rag_green"]     = brand.Palette.RagGreen,
                ["palette.rag_amber"]     = brand.Palette.RagAmber,
                ["palette.rag_red"]       = brand.Palette.RagRed,

                ["footer_text"]    = brand.FooterText,
                ["disclaimer"]     = brand.Disclaimer,
                ["copyright_mask"] = brand.CopyrightMask?.Replace("{{year}}", now.Year.ToString())
                                                         .Replace("{{company_name}}", brand.CompanyName) ?? "",

                ["date"]       = now.ToString("yyyy-MM-dd"),
                ["datetime"]   = now.ToString("yyyy-MM-dd HH:mm"),
                ["year"]       = now.Year.ToString(),
                ["author"]     = Environment.UserName ?? "",

                ["project_code"]   = TryGetProjParam(proj, BuiltInParameter.PROJECT_NUMBER)  ?? "",
                ["project_name"]   = TryGetProjParam(proj, BuiltInParameter.PROJECT_NAME)    ?? "",
                ["project_client"] = TryGetProjParam(proj, BuiltInParameter.CLIENT_NAME)     ?? "",
                ["project_status"] = TryGetProjParam(proj, BuiltInParameter.PROJECT_STATUS)  ?? "",
                ["project_issue_date"] = TryGetProjParam(proj, BuiltInParameter.PROJECT_ISSUE_DATE) ?? "",
            };
            return bag;
        }

        /// <summary>
        /// Substitute {{token}} placeholders in a string using the
        /// token bag. Missing tokens pass through unchanged so shop-
        /// floor edits to a template don't silently blank out.
        /// </summary>
        public static string Apply(string input, IDictionary<string, string> bag)
        {
            if (string.IsNullOrEmpty(input) || bag == null) return input ?? "";
            string result = input;
            foreach (var kv in bag)
                result = result.Replace("{{" + kv.Key + "}}", kv.Value ?? "");
            return result;
        }

        /// <summary>
        /// Prepend two comment rows to a CSV exporter so every
        /// .csv STING writes carries the corporate masthead.
        /// Call RIGHT AFTER opening the StreamWriter, before any
        /// data rows.
        /// </summary>
        public static void StampCsvHeader(StreamWriter w, Document doc, string documentCode = "")
        {
            if (w == null) return;
            var b = CorporateBrand.For(doc);
            var tokens = For(doc);
            string proj = tokens.TryGetValue("project_code", out var pc) ? pc : "";
            w.WriteLine($"# Generated by {b.CompanyName} {tokens["datetime"]}");
            if (!string.IsNullOrEmpty(documentCode))
                w.WriteLine($"# Document: {documentCode}");
            if (!string.IsNullOrEmpty(proj))
                w.WriteLine($"# Project: {proj}");
            if (!string.IsNullOrEmpty(b.Disclaimer))
                w.WriteLine($"# {b.Disclaimer}");
        }

        /// <summary>
        /// Return an XML comment node text containing the corporate
        /// masthead. Callers build their own XElement and inject.
        /// </summary>
        public static string StampXmlComment(Document doc, string documentCode = "")
        {
            var b = CorporateBrand.For(doc);
            var tokens = For(doc);
            var sb = new StringBuilder();
            sb.AppendLine();
            sb.AppendLine($"  Generated by {b.CompanyName} {tokens["datetime"]}");
            if (!string.IsNullOrEmpty(documentCode)) sb.AppendLine($"  Document: {documentCode}");
            if (tokens.TryGetValue("project_code", out var pc) && !string.IsNullOrEmpty(pc))
                sb.AppendLine($"  Project: {pc}");
            if (!string.IsNullOrEmpty(b.Disclaimer))
                sb.AppendLine($"  {b.Disclaimer}");
            sb.Append("  ");
            return sb.ToString();
        }

        private static string TryGetProjParam(ProjectInfo proj, BuiltInParameter bip)
        {
            try { return proj?.get_Parameter(bip)?.AsString() ?? ""; }
            catch { return ""; }
        }
    }
}
